#include "commands.h"
#include "cmd_opcodes.h"
#include "mesh.h"
#include "power_profile.h"
#include "ble/ble_service.h"
#include "display_manager.h"
#include "display_screens.h"
#include "battery.h"
#include "system_time.h"
#include "persist.h"
#include "secauth.h"
#include "factory.h"
#include <gfx/graphics.h>
#include <eink/ssd1675a.h>
#include <string.h>
#include <strings.h>
#include <stdio.h>
#include <stdlib.h>
#include <limits.h>
#include <zephyr/kernel.h>
#include <zephyr/bluetooth/bluetooth.h>
#include <zephyr/sys/reboot.h>
#ifdef CONFIG_MCUMGR_MGMT_NOTIFICATION_HOOKS
#include <zephyr/mgmt/mcumgr/mgmt/callbacks.h>
#endif

/* The DFU busy window (defined with the dispatcher, used by cmd_dfu above it). */
static void dfu_set_busy(bool on);
#include <app_version.h>
#include <pm_config.h>

/* Layout/variant id derived from the ACTUAL partition geometry generated by
 * Partition Manager — a single source of truth, so the reported id can never
 * disagree with the flashed layout (no -D plumbing to get wrong). v2 has a
 * dedicated factory_data partition + 12K settings; everything else is legacy. */
#if defined(PM_FACTORY_DATA_ADDRESS) && (PM_SETTINGS_STORAGE_SIZE == 0x3000)
#define APP_LAYOUT_ID 2
#else
#define APP_LAYOUT_ID 1
BUILD_ASSERT(PM_SETTINGS_STORAGE_SIZE == 0x2000,
	     "legacy layout must have 8K settings_storage — pm_static mismatch");
#endif

typedef void (*cmd_handler_t)(char *args);
/* flags bits for struct shell_cmd */
#define CMD_NOAUTH 0x01  /* runnable even when the access gate is on and unauthed */
#define CMD_MESH   0x02  /* broadcast-safe: may be invoked via a mesh flood */

/* A registry entry is identified by its stable `opcode` (cmd_opcodes.h); the
 * text `name` is just a human-typeable alias for the same opcode. Aliases that
 * map to one handler (UPDATE/APPLY, TIME/TIME=, VCOM=/DEBUG:VCOM=) deliberately
 * share an opcode. */
struct shell_cmd {
    uint8_t opcode;
    const char *name;
    cmd_handler_t handler;
    const char *help;
    uint8_t flags;
};
extern const struct shell_cmd commands[];

/* ── Line accumulator ───────────────────────────────────────────────────────
 * BLE NUS delivers raw chunks; we buffer until '\n' to guarantee whole commands
 * even when LUTW (148+ chars) spans multiple MTU packets.
 */
#define RX_BUF_SIZE 256
/* Text lines travel RX thread -> command thread (see cmd_thread below) in two
 * fixed slots cycled through a pair of fifos. The RX thread assembles the
 * line straight into a free slot, so a byte is written exactly once and the
 * slot is executed in place: no separate assembly buffer, no k_msgq copy —
 * RAM here is counted in bytes (the tag sits at ~98%). */
#define CMD_QUEUE_DEPTH 2
struct cmd_slot {
    void *fifo_reserved;            /* k_fifo bookkeeping */
    bool is_opcode;                 /* line[] is an opcode payload, not text */
    uint8_t opcode;
    char line[RX_BUF_SIZE];
};
static struct cmd_slot cmd_slots[CMD_QUEUE_DEPTH];
static K_FIFO_DEFINE(cmd_free);     /* slots waiting to be filled */
static K_FIFO_DEFINE(cmd_ready);    /* slots waiting to be run */
static struct cmd_slot *rx_slot;    /* text line the RX thread is filling, or NULL */
static bool rx_discard;             /* no slot was free: eat bytes to the next newline */
static struct cmd_slot *opc_slot;   /* opcode payload being received, or NULL */
static int  rx_len;

/* ── Binary opcode frame parser (NUS) ───────────────────────────────────────
 * A host may send a command as [OPC_MAGIC][opcode][len][payload] instead of a
 * text line, to save channel — this is the same inner PDU the mesh layer will
 * carry. The sentinel is only honored at a line boundary (rx_len == 0); the
 * payload accumulates into a queue slot of its own and runs on the command
 * thread like a text line would. With no free slot the frame is counted out
 * and dropped after one BUSY:cmd. */
enum opc_state {
    OPC_NONE = 0,     /* not inside an opcode frame */
    OPC_WANT_OP,      /* expecting the opcode byte */
    OPC_WANT_LEN,     /* expecting the payload length byte */
    OPC_WANT_PAYLOAD, /* accumulating payload bytes */
};
static enum opc_state opc_state;
static uint8_t opc_opcode;
static uint8_t opc_len;
static uint8_t opc_idx;

/* ── Frame buffer ────────────────────────────────────────────────────────── */
#define FB_SIZE 4736   /* 128 × 296 / 8 */

static uint8_t *fb_bw(void)  { return (uint8_t *)graphics_get_buffer(); }
static uint8_t *fb_red(void) { return (uint8_t *)graphics_get_red_buffer(); }
/* Bytes in one plane of the canvas the boot-time panel probe laid out
 * (4736 on 128x296, 15000 on 400x300). */
static int plane_size(void)  { return (int)graphics_get_canvas()->buffer_size; }
/* vstream frame size on the wire: the plane size at VSTREAM:start. FB_SIZE is
 * only the 128x296 default before the first stream. */
static uint16_t vs_fb = FB_SIZE;
static bool vs_half;   /* current frame carries VS_HALF_FLAG */
/* Rows a delta frame actually changed (full-res gate lines); only these go
 * over the bus at flush. INT_MAX/-1 = nothing changed. */
static int vs_dirty_y0 = INT_MAX, vs_dirty_y1 = -1;

static inline void vs_mark_dirty(int row)
{
    if (row < vs_dirty_y0) vs_dirty_y0 = row;
    if (row > vs_dirty_y1) vs_dirty_y1 = row;
}

/* ── Binary vstream (animation streaming over BLE) ──────────────────────────
 *
 * Wire protocol:
 *   Start : text command  VSTREAM:start[:preset] → device replies VSTREAM:ready
 *   Frame : [0xAA][0x55][type][len_hi][len_lo][payload*len][0xBB]
 *     0x00 RAW  — 4736 bytes uncompressed 1-bpp B&W
 *     0x01 RLE  — PackBits full frame
 *     0x02 DRLE — PackBits XOR-delta (current FB = prev frame, XOR in-place)
 *     0x03 RAW2 — BW plane then red/control plane (9472 bytes decoded)
 *     0x04 RLE2 — PackBits over both planes
 *     0x05 DRLE2— PackBits XOR-delta over both planes
 *   ACK   : "TELE:vs f=N ms=M\r\n" after every flush (host flow-control)
 *   Stop  : [0xCC][0xDD] binary escape for video/animation streams.
 *           This restores the screensaver after shutting down HV/fast BLE.
 *   Photo : [0xCC][0xDE] binary escape for still-photo tone streams.
 *           This shuts down HV/fast BLE but keeps the rendered photo on screen
 *           by leaving the screensaver disabled.
 *
 * PackBits:  ctrl bit7=1 → next byte × (ctrl&0x7F)+1 times (run)
 *            ctrl bit7=0 → next (ctrl+1) bytes literal
 */
#define VS_HDR1  0xAAu
#define VS_HDR2  0x55u
#define VS_FLUSH 0xBBu
#define VS_STOP1       0xCCu  /* Common binary stop escape prefix. */
#define VS_VIDEO_STOP2 0xDDu  /* Video stop: restore saver after stream ends. */
#define VS_PHOTO_STOP2 0xDEu  /* Photo stop: keep saver off so the image stays. */

#define VS_TYPE_RAW  0x00u
#define VS_TYPE_RLE  0x01u
#define VS_TYPE_DRLE 0x02u
#define VS_TYPE_RAW2  0x03u
#define VS_TYPE_RLE2  0x04u
#define VS_TYPE_DRLE2 0x05u

/* Bit 6 of the type byte marks a CRC-protected frame: a 2-byte CRC-16/CCITT
 * over the payload precedes the 0xBB flush. The low 6 bits still select the
 * encoding (0x00..0x05). Frames without this bit stay byte-for-byte the old
 * format, so old hosts and old firmware keep interoperating. */
#define VS_CRC_FLAG  0x40u
/* Type-byte flag: the frame is (W/2) x (H/2) and is pixel-doubled on decode.
 * A lossy 4x payload cut for video on the 400x300 panel, where BLE, not the
 * display, paces the stream. Low bits still select the encoding. */
#define VS_HALF_FLAG 0x20u
#define VS_TYPE_MASK 0x3Fu

typedef enum {
    VS_IDLE, VS_HDR2_WAIT, VS_TYPE_RD, VS_LEN_HI, VS_LEN_LO,
    VS_DATA, VS_CRC_HI, VS_CRC_LO, VS_FLUSH_WAIT, VS_STOP2_WAIT
} vs_state_t;

typedef struct {
    int8_t  mode;   /* 0=ctrl  1=literal  2=run_first_byte  3=run_repeat */
    uint8_t count;
    uint8_t val;
} rle_dec_t;

static vs_state_t vs_state;
static uint8_t    vs_type;
static uint16_t   vs_plen;   /* compressed payload length */
static uint16_t   vs_prx;    /* compressed bytes received */
static uint16_t   vs_dec;    /* uncompressed bytes written to FB */
static rle_dec_t  vs_rle;
static bool       vstream_active;
static int        vs_frame_count;
static bool       vs_has_crc;   /* current frame carries a CRC-16 trailer */
static uint16_t   vs_crc;       /* running CRC-16/CCITT over received payload */
static uint16_t   vs_crc_rx;    /* CRC-16 from the frame trailer (host-computed) */
static bool       vs_poisoned;  /* FB corruption detected — skip frames until a
                                 * full RAW/RLE keyframe overwrites the FB */

/* Watchdog: if no frame flush arrives within this window, abort the stream
 * and restore the screensaver so the device doesn't stay frozen. */
#define VS_WATCHDOG_MS 30000
static struct k_work_delayable vs_watchdog_work;
static struct k_work_sync vs_watchdog_sync;

/* Tear the stream down. Deliberately does NOT cancel the watchdog: the watchdog
 * handler is one of the callers and cannot wait on the work it is running. */
static void vs_teardown(bool restore_screensaver) {
    bool was_active = vstream_active;

    /* Wait for any in-progress pipelined display refresh to finish before
     * powering down HV rails. Safe to call even when no refresh is active. */
    ssd1675a_wait_busy();
    ble_service_set_streaming_mode(false);
    display_manager_set_stream_write_red_plane(false);
    if (was_active) {
        vs_state       = VS_IDLE;
        vstream_active = false;
        vs_frame_count = 0;
        display_manager_set_keep_on(false);
    }
    /* Video/animation wants the device to resume its saver after stop.
     * Still-photo rendering wants a sleeping display with the final image left
     * alone, so that path passes false here — and a redundant stop after it
     * must not wake the saver either, or the photo is overwritten. */
    if (restore_screensaver && was_active) {
        display_manager_enable_screensaver(true);
    }
}

static void vs_exit_streaming(bool restore_screensaver) {
    /* _sync, not the plain cancel: the 30 s watchdog may already be running
     * vs_teardown on the system workqueue, and the plain cancel does not wait
     * for a handler that has started — both contexts would then drive the SPI
     * bus and rewrite the stream state at once. */
    k_work_cancel_delayable_sync(&vs_watchdog_work, &vs_watchdog_sync);
    vs_teardown(restore_screensaver);
}

static bool vs_type_is_dual(uint8_t type)
{
    return type == VS_TYPE_RAW2 || type == VS_TYPE_RLE2 || type == VS_TYPE_DRLE2;
}

static bool vs_type_is_raw(uint8_t type)
{
    return type == VS_TYPE_RAW || type == VS_TYPE_RAW2;
}

static bool vs_type_is_delta(uint8_t type)
{
    return type == VS_TYPE_DRLE || type == VS_TYPE_DRLE2;
}

static void vs_watchdog_handler(struct k_work *work) {
    ARG_UNUSED(work);
    if (vstream_active) {
        ble_printf("VSTREAM:timeout\r\n");
        /* vs_teardown, NOT vs_exit_streaming: this runs on the system
         * workqueue as this very work item, and vs_exit_streaming would
         * sync-cancel the work it is executing — the completion that releases
         * the wait only happens after this handler returns, so it would block
         * the workqueue forever. Cancelling is pointless here anyway: the
         * timer has already fired. */
        vs_teardown(true);
    }
}

/* Track bytes written via FW:/RW: since last clear — reported in FAPPLY. */
static int fw_written;
static int rw_written;

/* When host_mode=true the device sends machine-readable TELE: lines after
 * every display update so the host app can track actual frame timing. */
static bool host_mode = false;

/* ── Hex helpers ─────────────────────────────────────────────────────────── */

static int hex_nibble(char c)
{
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    return -1;
}

static int hex_byte(const char *s)
{
    int hi = hex_nibble(s[0]);
    int lo = hex_nibble(s[1]);
    if (hi < 0 || lo < 0) return -1;
    return (hi << 4) | lo;
}

/* Shared "offset:HH.." prologue of FW:, RW: and LW:. Returns the hex payload
 * and writes *offset, or NULL when the colon separator is missing. An offset
 * that does not fit an int comes back as -1 so range_ok() rejects it. */
static const char *parse_offset_prefix(char *args, int *offset)
{
    char *endptr;
    long value = strtol(args, &endptr, 10);

    if (*endptr != ':') {
        return NULL;
    }
    *offset = (value < 0 || value > INT_MAX) ? -1 : (int)value;
    return endptr + 1;
}

/* True when writing nbytes at offset stays inside a limit-sized buffer.
 * Phrased as (offset <= limit - nbytes), NOT (offset + nbytes > limit): offset
 * arrives straight off the wire and can be INT_MAX, where that addition is
 * signed overflow — it wraps negative and the naive check passes. */
static bool range_ok(int offset, int nbytes, int limit)
{
    return offset >= 0 && nbytes >= 0 && nbytes <= limit && offset <= limit - nbytes;
}

/* ── Vstream helpers ─────────────────────────────────────────────────────── */

/* CRC-16/CCITT-FALSE (poly 0x1021, init 0xFFFF, MSB-first) — running update.
 * Must match the host's crc16_ccitt().
 *
 * Nibble table, not the byte table the RAM budget can't afford and not the
 * table-free shift loop that came before it: 16 entries is 32 bytes of .rodata
 * and zero RAM, and it turns eight shift-and-test iterations per byte into two
 * lookups. On a RAW2 frame the old loop ran 240 000 iterations — about 15 ms of
 * the receive path, on the BLE RX thread, per frame.
 *
 * Equivalence to the shift loop was checked exhaustively over the whole state
 * space (all 65536 CRC values x 256 input bytes) and against the standard
 * "123456789" -> 0x29B1 vector. */
static const uint16_t vs_crc16_nib[16] = {
    0x0000, 0x1021, 0x2042, 0x3063, 0x4084, 0x50A5, 0x60C6, 0x70E7,
    0x8108, 0x9129, 0xA14A, 0xB16B, 0xC18C, 0xD1AD, 0xE1CE, 0xF1EF,
};

static inline uint16_t vs_crc16_update(uint16_t crc, uint8_t b)
{
    crc = (uint16_t)((crc << 4) ^ vs_crc16_nib[((crc >> 12) ^ (b >> 4)) & 0x0Fu]);
    crc = (uint16_t)((crc << 4) ^ vs_crc16_nib[((crc >> 12) ^ (b & 0x0Fu)) & 0x0Fu]);
    return crc;
}

static void vs_reset_frame(void) {
    vs_prx = 0;
    vs_dec = 0;
    vs_dirty_y0 = INT_MAX;
    vs_dirty_y1 = -1;
    vs_rle.mode = 0;
    vs_rle.count = 0;
    vs_rle.val = 0;
    vs_crc = 0xFFFFu;
    vs_crc_rx = 0;
}

/* Bytes of one plane on the wire: the panel plane, or a quarter of it for a
 * half-resolution frame ((W/2) x (H/2), see VS_HALF_FLAG). */
static inline uint16_t vs_plane_bytes(void)
{
    return vs_half ? (uint16_t)(vs_fb / 4) : vs_fb;
}

/* Half-resolution frames land as 2x2 pixel blocks: each decoded byte (8
 * half-pixels) becomes two bytes in each of two framebuffer rows through a
 * nibble-doubling table. Doubling is linear over XOR, so a DRLE delta applied
 * this way on top of a half-res keyframe is exactly the doubled half-res
 * image — no extra buffer, no per-frame state beyond vs_dec. */
static const uint8_t vs_nib_dbl[16] = {
    0x00, 0x03, 0x0C, 0x0F, 0x30, 0x33, 0x3C, 0x3F,
    0xC0, 0xC3, 0xCC, 0xCF, 0xF0, 0xF3, 0xFC, 0xFF,
};

static inline void vs_write_byte(uint8_t b) {
    const bool dual = vs_type_is_dual(vs_type);
    const uint16_t plane = vs_plane_bytes();
    const uint16_t max_dec = dual ? (plane * 2) : plane;
    if (vs_dec >= max_dec) return;

    uint8_t *fb;
    uint16_t off = vs_dec;
    if (dual && off >= plane) {
        fb = fb_red();
        off -= plane;
    } else {
        fb = fb_bw();
    }

    if (fb) {   /* a B/W-only panel has no red plane: swallow that half */
        const bool delta = vs_type_is_delta(vs_type);
        const int stride = ssd1675a_width() / 8;   /* full-res bytes per row */
        if (!vs_half) {
            fb[off] = delta ? (fb[off] ^ b) : b;
            if (delta && b) {
                vs_mark_dirty(off / stride);
            }
        } else {
            const int hstride = stride / 2;
            const int hy = off / hstride, hx = off % hstride;
            uint8_t *p0 = fb + (2 * hy) * stride + 2 * hx;
            uint8_t *p1 = p0 + stride;
            const uint8_t d0 = vs_nib_dbl[b >> 4], d1 = vs_nib_dbl[b & 0x0F];
            if (delta) {
                p0[0] ^= d0; p0[1] ^= d1; p1[0] ^= d0; p1[1] ^= d1;
                if (b) {
                    vs_mark_dirty(2 * hy);
                    vs_mark_dirty(2 * hy + 1);
                }
            } else {
                p0[0] = d0;  p0[1] = d1;  p1[0] = d0;  p1[1] = d1;
            }
        }
    }
    vs_dec++;
}

static void vs_rle_feed(uint8_t b) {
    /* Drain pending run bytes first — they don't consume compressed input.
     * Without this, each run-continuation output would eat one real input
     * byte (the next instruction), corrupting the entire stream. */
    while (vs_rle.mode == 3) {
        vs_write_byte(vs_rle.val);
        if (--vs_rle.count == 0) { vs_rle.mode = 0; break; }
    }
    /* Now consume the actual compressed byte. */
    switch (vs_rle.mode) {
    case 0:
        if (b & 0x80) { vs_rle.count = (b & 0x7F) + 1; vs_rle.mode = 2; }
        else          { vs_rle.count = b + 1;            vs_rle.mode = 1; }
        break;
    case 1:
        vs_write_byte(b);
        if (--vs_rle.count == 0) vs_rle.mode = 0;
        break;
    case 2:
        vs_rle.val = b;
        vs_write_byte(b);
        if (--vs_rle.count == 0) vs_rle.mode = 0;
        else vs_rle.mode = 3;
        break;
    }
}

static void vs_flush_frame(void) {
    const bool dual = vs_type_is_dual(vs_type);
    const uint16_t max_dec = dual ? (vs_plane_bytes() * 2) : vs_plane_bytes();

    /* Flush any trailing run bytes that arrived at end of compressed stream. */
    if (!vs_type_is_raw(vs_type)) {
        while (vs_rle.mode == 3 && vs_dec < max_dec) {
            vs_write_byte(vs_rle.val);
            if (--vs_rle.count == 0) { vs_rle.mode = 0; break; }
        }
    }

    /* XOR checksum of the decoded framebuffer — legacy host integrity field,
     * superseded by the wire CRC-16 below (the `wc`/`rs` fields). Computing it
     * walks the whole framebuffer — 15 000 bytes on a 400x300 panel, 30 000
     * when both planes are live — and it sat right before the wait-for-BUSY,
     * so it landed squarely in the gap between frames. Only host_mode consumes
     * the value, so only host_mode pays for it; everyone else reports 00 and
     * gets the milliseconds back. */
    uint8_t crc = 0;
    if (host_mode) {
        const uint8_t *fb = fb_bw();
        for (int i = 0; i < vs_fb; i++) crc ^= fb[i];
        if (dual) {
            const uint8_t *fr = fb_red();   /* NULL on a B/W-only panel */
            for (int i = 0; fr && i < vs_fb; i++) crc ^= fr[i];
        }
    }

    /* Wire-CRC verdict (L0). A frame with no CRC trailer is trusted as before.
     * A CRC mismatch means the payload arrived corrupt; for a delta the in-place
     * XOR has already mutated the FB, so mark it poisoned and don't show it. */
    const bool crc_bad = vs_has_crc && (vs_crc != vs_crc_rx);
    if (crc_bad) {
        vs_poisoned = true;
    } else if (!vs_type_is_delta(vs_type)) {
        /* A clean full frame (RAW/RLE) overwrites every FB byte → heals. */
        vs_poisoned = false;
    }
    /* L1: while poisoned, even a clean delta can't be trusted (it built on a
     * corrupt FB), so skip it too and keep requesting a keyframe. The display
     * holds the last good frame until a full keyframe arrives. */
    const bool show = !crc_bad && !vs_poisoned;
    const bool want_resync = crc_bad || vs_poisoned;

    int32_t ms = 0, wait_ms = 0, spi_ms = 0;
    if (show) {
        /* Pipeline: wait for the PREVIOUS frame's refresh (triggered without
         * blocking, so it overlapped this frame's BLE transfer), then trigger
         * this one. ms includes the wait so the host sees real display timing;
         * w/s split it into the wave remainder and the SPI burst + trigger. */
        int64_t t0 = k_uptime_get();
        ssd1675a_wait_busy();
        int64_t t1 = k_uptime_get();
        display_manager_set_keep_on(true);
        display_manager_set_stream_write_red_plane(dual);
        if (vs_type_is_delta(vs_type) && !dual) {
            /* Only the rows the delta touched need to reach the controller;
             * an unchanged frame writes nothing and just refreshes. */
            display_manager_update_partial_rows_nowait(vs_dirty_y0, vs_dirty_y1);
        } else {
            display_manager_update_partial_nowait();
        }
        int64_t t2 = k_uptime_get();
        wait_ms = (int32_t)(t1 - t0);
        spi_ms = (int32_t)(t2 - t1);
        ms = (int32_t)(t2 - t0);
    }

    vs_frame_count++;
    /* Reset watchdog — host is alive and sending frames (skipped ones too). */
    k_work_reschedule(&vs_watchdog_work, K_MSEC(VS_WATCHDOG_MS));
    /* ACK: legacy fields (f/ms/dec/crc) plus the wire-CRC verdict wc and a
     * resync request rs=1 (host should send a full keyframe). Old hosts simply
     * ignore the two trailing fields. */
    const int rows = (vs_type_is_delta(vs_type) && !dual)
                         ? ((vs_dirty_y1 >= vs_dirty_y0) ? vs_dirty_y1 - vs_dirty_y0 + 1 : 0)
                         : ssd1675a_height();
    ble_printf("TELE:vs f=%d ms=%d dec=%d crc=%02x wc=%s rs=%d w=%d s=%d r=%d\r\n",
               vs_frame_count, (int)ms, (int)vs_dec, (unsigned)crc,
               vs_has_crc ? (crc_bad ? "bad" : "ok") : "na",
               want_resync ? 1 : 0, (int)wait_ms, (int)spi_ms, rows);
}

static void vs_process_byte(uint8_t b) {
    switch (vs_state) {
    case VS_IDLE:
        if      (b == VS_HDR1)  vs_state = VS_HDR2_WAIT;
        else if (b == VS_STOP1) vs_state = VS_STOP2_WAIT;
        break;
    case VS_HDR2_WAIT:
        vs_state = (b == VS_HDR2) ? VS_TYPE_RD : VS_IDLE;
        break;
    case VS_TYPE_RD:
        vs_has_crc = (b & VS_CRC_FLAG) != 0;
        vs_half    = (b & VS_HALF_FLAG) != 0;
        vs_type    = b & VS_TYPE_MASK & (uint8_t)~VS_HALF_FLAG;
        vs_state   = (vs_type <= VS_TYPE_DRLE2) ? VS_LEN_HI : VS_IDLE;
        break;
    case VS_LEN_HI:
        vs_plen  = (uint16_t)b << 8;
        vs_state = VS_LEN_LO;
        break;
    case VS_LEN_LO:
        vs_plen |= b;
        vs_reset_frame();
        /* Zero-length payload (e.g. an empty delta) still carries a CRC trailer
         * when the CRC bit is set, so route to the CRC states either way. */
        vs_state = (vs_plen > 0) ? VS_DATA
                 : (vs_has_crc ? VS_CRC_HI : VS_FLUSH_WAIT);
        break;
    case VS_DATA:
        vs_prx++;
        vs_crc = vs_crc16_update(vs_crc, b);  /* CRC covers raw payload bytes */
        if (vs_type_is_raw(vs_type)) vs_write_byte(b);
        else                         vs_rle_feed(b);
        if (vs_prx >= vs_plen)
            vs_state = vs_has_crc ? VS_CRC_HI : VS_FLUSH_WAIT;
        break;
    case VS_CRC_HI:
        vs_crc_rx = (uint16_t)b << 8;
        vs_state  = VS_CRC_LO;
        break;
    case VS_CRC_LO:
        vs_crc_rx |= b;
        vs_state   = VS_FLUSH_WAIT;
        break;
    case VS_FLUSH_WAIT:
        if (b == VS_FLUSH) vs_flush_frame();  /* flush_frame handles pending run drain */
        vs_state = VS_IDLE;
        break;
    case VS_STOP2_WAIT:
        if (b == VS_VIDEO_STOP2) {
            /* [CC DD] = video semantics: stop streaming and restore saver. */
            vs_exit_streaming(true);
            ble_printf("VSTREAM:stopped\r\n");
        } else if (b == VS_PHOTO_STOP2) {
            /* [CC DE] = still-photo semantics: stop streaming, power down
             * display/HV, but do not restart saver over the rendered photo. */
            vs_exit_streaming(false);
            ble_printf("VSTREAM:photo_stopped\r\n");
        }
        vs_state = VS_IDLE;
        break;
    }
}

/* ── Standard commands ───────────────────────────────────────────────────── */

static void cmd_help(char *args)
{
    ble_printf("cmds (op A5 <op> <len> <payload>):\r\n");
    for (int i = 0; commands[i].name != NULL; i++) {
        ble_printf("  %02X %s — %s\r\n",
                   commands[i].opcode, commands[i].name, commands[i].help);
    }
}

static void cmd_cls(char *args)
{
    display_manager_enable_screensaver(false);
    display_manager_clear();
    ble_printf("cleared\r\n");
}

static void cmd_clean(char *args)
{
    display_manager_enable_screensaver(false);
    ble_printf("cleaning (7 cycles)...\r\n");
    display_manager_clean();
    ble_printf("done\r\n");
}

static void cmd_nuke(char *args)
{
    int n = (args && *args) ? atoi(args) : 20;
    if (n < 5)  n = 5;
    if (n > 50) n = 50;
    display_manager_enable_screensaver(false);
    // Each cycle: 3 full updates (B/W/R) × ~15s each = ~45s/cycle
    ble_printf("NUKE: %d cycles (~%d min) — clearing ghost...\r\n",
               n, (n * 3 * 15 + 30) / 60);
    display_manager_deep_clean(n);
    ble_printf("NUKE: done\r\n");
}

static void cmd_saver(char *args)
{
    display_manager_enable_screensaver(true);
    ble_printf("saver enabled\r\n");
}

static void cmd_update(char *args)
{
    if (!host_mode) ble_printf("updating...\r\n");
    int64_t t0 = k_uptime_get();
    /* A full cycle, not "a redraw of whatever kind the screensaver felt like":
     * this is the command a host reaches for when the panel looks wrong, and a
     * partial refresh cannot fix ghosting or a stale red plane. */
    display_manager_request_full_update();
    int32_t elapsed = (int32_t)(k_uptime_get() - t0);
    if (host_mode) {
        ble_printf("TELE:full time=%dms lut=%s\r\n",
                   (int)elapsed, ssd1675a_get_use_custom_lut() ? "custom" : "builtin");
    } else {
        ble_printf("done %dms\r\n", (int)elapsed);
    }
}

static void cmd_fast(char *args)
{
    if (!host_mode) ble_printf("fast update...\r\n");
    int64_t t0 = k_uptime_get();
    display_manager_update_partial();
    int32_t elapsed = (int32_t)(k_uptime_get() - t0);
    if (host_mode) {
        ble_printf("TELE:fast time=%dms lut=%s\r\n",
                   (int)elapsed, ssd1675a_get_use_custom_lut() ? "custom" : "builtin");
    } else {
        ble_printf("done %dms\r\n", (int)elapsed);
    }
}

static void cmd_test(char *args)
{
    ble_printf("Starting Partial Stress Test (Infinite)... Reset to stop.\r\n");
    display_manager_enable_screensaver(false);

    int32_t count = 0;
    bt_addr_le_t addr = {0};
    size_t count_id = 1;
    char addr_str[BT_ADDR_LE_STR_LEN] = "Unknown";

    bt_id_get(&addr, &count_id);
    bt_addr_le_to_str(&addr, addr_str, sizeof(addr_str));

    display_screens_render_text("INITIAL CLEAN...\nPlease Wait");
    display_manager_force_update();

    int64_t last_time = k_uptime_get();

    while (1) {
        int64_t start = k_uptime_get();
        int32_t delta = (int32_t)(start - last_time);
        last_time = start;

        display_screens_render_partial_test(count++, start, delta, addr_str);
        display_manager_update_partial();
        k_msleep(1);
    }
}

static void cmd_mode(char *args)
{
    if (!args || !*args) { ble_printf("usage: MODE: 0-7\r\n"); return; }
    int m = atoi(args);
    display_manager_set_partial_mode(m);
    ble_printf("Mode Set: %d (0=T,1=B,2=S,3=C,4=ToneDark,5=ToneLight,6=ToneBidirFast,7=ToneBidir)\r\n", m);
}

static void cmd_text(char *args)
{
    if (!args || !*args) return;
    display_manager_enable_screensaver(false);
    display_manager_show_text(args);
    ble_printf("drawn\r\n");
}

static void cmd_paltest(char *args)
{
    ARG_UNUSED(args);
    display_manager_enable_screensaver(false);
    ble_printf("PALTEST: rendering spatial B/W/R palette...\r\n");
    display_manager_show_palette_test();
    ble_printf("PALTEST: done\r\n");
}

static void cmd_tonetest(char *args)
{
    ARG_UNUSED(args);
    display_manager_enable_screensaver(false);
    ble_printf("TONETEST: white base + 8 black-only pulse passes...\r\n");
    display_manager_run_tone_test();
    ble_printf("TONETEST: done (use CLEAN/NUKE if residual ghosting stays)\r\n");
}

static void cmd_rot(char *args)
{
    if (!args || !*args) { ble_printf("usage: ROT: 0-3\r\n"); return; }
    int r = atoi(args);
    display_manager_set_rotation(r);
    ble_printf("rotation: %d\r\n", r);
}

static void cmd_batt(char *args)
{
    /* Keep the "bat: %d mv" shape even on a failed read — hosts sscanf it.
     * 0 mV was the pre-existing sentinel; the error itself goes to the log. */
    int mv = battery_read_mv();
    ble_printf("bat: %d mv\r\n", mv < 0 ? 0 : mv);
}

/* TIME HH:MM:SS DD.MM.YYYY */
static void cmd_time(char *args)
{
    if (!args || strlen(args) < 10) {
        ble_printf("usage: TIME HH:MM:SS DD.MM.YYYY\r\n");
        return;
    }
    int h, m, s, D, M, Y;
    if (sscanf(args, "%d:%d:%d %d.%d.%d", &h, &m, &s, &D, &M, &Y) == 6) {
        set_system_time(h, m, s, D, M, Y);
        display_manager_force_update();
        ble_printf("Time Set\r\n");
    } else {
        ble_printf("parse error\r\n");
    }
}

/* TIME=HH:MM:SS — lut_tester_host compatible; preserves current date */
static void cmd_time_eq(char *args)
{
    if (!args || !*args) { ble_printf("usage: TIME=HH:MM:SS\r\n"); return; }
    int h = 0, m = 0, s = 0;
    sscanf(args, "%d:%d:%d", &h, &m, &s);
    struct tm t = {0};
    get_system_time(&t);
    set_system_time(h, m, s, t.tm_mday, t.tm_mon + 1, t.tm_year + 1900);
    display_manager_force_update();
    ble_printf("TIME set %d:%s%d:%s%d\r\n",
               h, m < 10 ? "0" : "", m, s < 10 ? "0" : "", s);
}

static void cmd_dsaver(char *args)
{
    if (!args || !*args) {
        ble_printf("usage: DSAVER 0/1\r\n");
        return;
    }
    int mode = atoi(args);
    display_manager_enable_screensaver(true);
    display_manager_set_screensaver_mode(
        mode ? SCREENSAVER_MODE_DYNAMIC : SCREENSAVER_MODE_STATIC);
    ble_printf("Dynamic Saver: %s\r\n", mode ? "ON" : "OFF");
}

static void cmd_anim(char *args)
{
    ble_printf("Starting Animation (Reset to stop)...\r\n");
    display_manager_enable_screensaver(false);
    display_manager_set_keep_on(true);

    int x = 10, y = 10, vx = 4, vy = 4, size = 20, frame = 0;
    int width  = graphics_get_width();
    int height = graphics_get_height();

    graphics_clear(GFX_WHITE);
    display_manager_force_update();

    // Charge ±15V rails once — one-time ~600ms cost.
    // Subsequent frames use update_frame_stream() which skips HV cycling.
    display_manager_begin_streaming();

    int64_t last_ms = k_uptime_get();

    while (1) {
        x += vx;  y += vy;
        if (x <= 0 || x + size >= width)  vx = -vx;
        if (y <= 0 || y + size >= height) vy = -vy;
        x = (x < 0) ? 0 : (x + size > width  ? width  - size : x);
        y = (y < 0) ? 0 : (y + size > height ? height - size : y);

        int64_t now = k_uptime_get();
        int32_t delta = (int32_t)(now - last_ms);
        last_ms = now;

        display_screens_render_animation_frame(x, y, size, frame++, delta);
        display_manager_update_frame_stream();  // ~64ms: LUT wave only, no HV cycle

        if (frame % 50 == 0) ble_printf("Anim #%d  %dms/frame\r\n", frame, (int)delta);
    }
    // Note: end_streaming() unreachable in infinite loop; HV discharges on reset.
}

static void cmd_debug_vcom(char *args)
{
    if (!args || !*args) return;
    uint32_t val = strtoul(args, NULL, 16);
    ssd1675a_set_vcom_register((uint8_t)val);
    ble_printf("VCOM=0x%02X\r\n", (uint8_t)val);
}

static void cmd_debug_lut(char *args)
{
    if (!args || !*args) return;
    char *colon = strchr(args, ':');
    if (colon) {
        *colon = '\0';
        int idx = atoi(args);
        uint32_t val = strtoul(colon + 1, NULL, 16);
        ssd1675a_set_lut_byte(idx, (uint8_t)val);
        ble_printf("LUT[%d]=0x%02X\r\n", idx, (uint8_t)val);
    }
}

/* ── LUT tester commands (lut_tester_host compatible) ───────────────────── */

/* LUTW:HH..  — write all 70 LUT bytes at once */
static void cmd_lutw(char *args)
{
    int expected = SSD1675A_LUT_SIZE * 2;
    int got = (int)strlen(args);
    if (got != expected) {
        ble_printf("LUTW: need %d hex, got %d\r\n", expected, got);
        return;
    }
    for (int i = 0; i < SSD1675A_LUT_SIZE; i++) {
        int b = hex_byte(args + i * 2);
        if (b < 0) { ble_printf("LUTW: bad hex at %d\r\n", i * 2); return; }
        ssd1675a_set_lut_byte(i, (uint8_t)b);
    }
    ssd1675a_set_use_custom_lut(true);
    ble_printf("LUT written (%d bytes) — custom LUT active\r\n", SSD1675A_LUT_SIZE);
}

/* LW:idx:HH..  — write N bytes starting at idx */
static void cmd_lw(char *args)
{
    int idx;
    const char *hex = parse_offset_prefix(args, &idx);
    if (!hex) { ble_printf("usage: LW:idx:HH..\r\n"); return; }
    int nbytes = (int)strlen(hex) / 2;
    if (!range_ok(idx, nbytes, SSD1675A_LUT_SIZE)) {
        ble_printf("LW: out of range\r\n"); return;
    }
    for (int i = 0; i < nbytes; i++) {
        int b = hex_byte(hex + i * 2);
        if (b < 0) { ble_printf("LW: bad hex at %d\r\n", i); return; }
        ssd1675a_set_lut_byte(idx + i, (uint8_t)b);
    }
    ssd1675a_set_use_custom_lut(true);
    ble_printf("LW: wrote %d bytes from [%d] — custom LUT active\r\n", nbytes, idx);
}

/* L:n=HH | L:DUMP | L:RESET */
static void cmd_l_byte(char *args)
{
    if (strcmp(args, "DUMP") == 0) {
        ble_printf("LUT[70]:\r\n");
        for (int i = 0; i < SSD1675A_LUT_SIZE; i++) {
            ble_printf("%02X%s", ssd1675a_get_lut_byte(i),
                (i % 10 == 9 || i == SSD1675A_LUT_SIZE - 1) ? "\r\n" : " ");
        }
        return;
    }
    if (strcmp(args, "RESET") == 0) {
        ssd1675a_reset_lut();
        ble_printf("LUT reset\r\n");
        return;
    }
    char tmp[32];
    strncpy(tmp, args, sizeof(tmp) - 1);
    tmp[sizeof(tmp) - 1] = '\0';
    char *eq = strchr(tmp, '=');
    if (!eq) { ble_printf("usage: L:n=HH\r\n"); return; }
    *eq = '\0';
    int idx = atoi(tmp);
    uint8_t val = (uint8_t)strtoul(eq + 1, NULL, 16);
    ssd1675a_set_lut_byte(idx, val);
    ssd1675a_set_use_custom_lut(true);
    ble_printf("L[%d]=0x%02X — custom LUT active\r\n", idx, val);
}

/* Fast connection parameters were requested for a FW:/RW: transfer and must
 * be released by the FAPPLY that ends it. */
static bool frame_xfer_fast;

/* Body of FW: and RW: — same wire shape, different target plane. Decodes in
 * place, so a bad nibble part-way leaves the earlier bytes written (the
 * host reconciles via the FAPPLY byte count). `tag` selects the reply prefix. */
static void fb_write(char *args, uint8_t *buf, int *counter, const char *tag)
{
    int offset;
    const char *hex = parse_offset_prefix(args, &offset);
    if (!hex) { ble_printf("%s:err no colon\r\n", tag); return; }
    int hexlen = (int)strlen(hex);
    if (hexlen & 1) { ble_printf("%s:err odd len %d\r\n", tag, hexlen); return; }
    int nbytes = hexlen / 2;
    if (!range_ok(offset, nbytes, plane_size())) {
        ble_printf("%s:OOB off=%d n=%d\r\n", tag, offset, nbytes); return;
    }
    if (!buf) { ble_printf("%s:no plane\r\n", tag); return; }

    /* A frame is 100-313 write-without-response packets. On the idle
     * connection parameters (100-200 ms, latency 4) a macOS/Chrome host
     * overruns its own queue and silently drops some — and the FAPPLY behind
     * them. Borrow vstream's fast parameters for the transfer; the closing
     * FAPPLY gives them back. */
    if (offset == 0 && !frame_xfer_fast) {
        frame_xfer_fast = true;
        ble_service_set_streaming_mode(true);
    }

    for (int i = 0; i < nbytes; i++) {
        int b = hex_byte(hex + i * 2);
        if (b < 0) {
            ble_printf("%s:badchar off=%d pos=%d c=%02X\r\n",
                       tag, offset, i, (uint8_t)hex[i * 2]);
            return;
        }
        buf[offset + i] = (uint8_t)b;
    }
    *counter += nbytes;

    /* Progress for the host: one line per 2 KB and at the end of the plane,
     * so a 15000 B transfer over a phone shows movement instead of silence. */
    int end = offset + nbytes;
    if ((end / 2048) != (offset / 2048) || end >= plane_size()) {
        ble_printf("%s:rx %d/%d\r\n", tag, end, plane_size());
    }
}

/* FW:offset:HH..  — write BW frame bytes */
static void cmd_fw(char *args)
{
    fb_write(args, fb_bw(), &fw_written, "FW");
}

/* RW:offset:HH..  — write Red frame bytes. A single-plane panel has no red
 * buffer: the bytes land in the only frame buffer and the host must follow
 * them with FAPPLY RED (stages them into the controller's red RAM) before it
 * writes the B/W frame with FW: and applies. */
static void cmd_rw(char *args)
{
    fb_write(args, fb_red() ? fb_red() : fb_bw(), &rw_written, "RW");
}

/* FAPPLY — push FW/RW-written frame buffers to display.
 * Screensaver is disabled first; a short sleep lets its thread finish
 * the current render cycle before we push our frame.
 * FAPPLY RED / FAPPLY:RED — stage the RW: bytes as the red plane on a
 * single-plane panel (see cmd_rw); no refresh yet. */
static void cmd_fapply(char *args)
{
    while (args && (*args == ':' || *args == ' ')) {
        args++;
    }
    if (args && strncasecmp(args, "RED", 3) == 0) {
        display_manager_enable_screensaver(false);
        k_msleep(150);
        display_manager_stage_red_plane();
        int rw = rw_written;
        rw_written = 0;
        ble_printf("FAPPLY:red staged rw=%d\r\n", rw);
        return;
    }
    display_manager_enable_screensaver(false);
    k_msleep(150);  /* wait for screensaver thread to finish current cycle */
    int bw = fw_written, rw = rw_written;
    fw_written = 0;
    rw_written = 0;
    if (!host_mode) ble_printf("FAPPLY bw=%d rw=%d...\r\n", bw, rw);
    int64_t t0 = k_uptime_get();
    display_manager_force_update();
    int32_t elapsed = (int32_t)(k_uptime_get() - t0);
    if (frame_xfer_fast) {
        frame_xfer_fast = false;
        ble_service_set_streaming_mode(false);
    }
    if (host_mode) {
        ble_printf("TELE:fapply time=%dms bw=%d rw=%d lut=%s\r\n",
                   (int)elapsed, bw, rw,
                   ssd1675a_get_use_custom_lut() ? "custom" : "builtin");
    } else {
        ble_printf("FAPPLY done %dms\r\n", (int)elapsed);
    }
}

/* SS:0/1 — screensaver on/off (lut_tester_host compatible) */
static void cmd_ss(char *args)
{
    if (!args || !*args) { ble_printf("usage: SS:0/1\r\n"); return; }
    int en = atoi(args);
    display_manager_enable_screensaver(en != 0);
    ble_printf("screensaver %s\r\n", en ? "ON" : "OFF");
}

/* VCOM=HH — set VCOM register */
static void cmd_vcom(char *args)
{
    if (!args || !*args) { ble_printf("usage: VCOM=HH\r\n"); return; }
    uint8_t v = (uint8_t)strtoul(args, NULL, 16);
    ssd1675a_set_vcom_register(v);
    ble_printf("VCOM=0x%02X\r\n", v);
}

/* HOST:0/1 — switch device into machine-readable telemetry mode */
static void cmd_host(char *args)
{
    if (!args || !*args) {
        ble_printf("HOST:%s\r\n", host_mode ? "1" : "0");
        return;
    }
    host_mode = (atoi(args) != 0);
    display_manager_set_tele_enabled(host_mode);
    /* Always respond in human-readable format to confirm the switch */
    ble_printf("HOST:%s\r\n", host_mode ? "1" : "0");
}

/* STAT — snapshot of current LUT test timing stats + device state */
static void cmd_stat(char *args)
{
    int32_t frame, cur_ms, min_ms, max_ms;
    display_manager_get_lut_test_stats(&frame, &cur_ms, &min_ms, &max_ms);
    ble_printf("STAT:lut=%s host=%s frame=%d last=%d min=%d max=%d\r\n",
               ssd1675a_get_use_custom_lut() ? "custom" : "builtin",
               host_mode ? "1" : "0",
               (int)frame, (int)cur_ms, (int)min_ms, (int)max_ms);
}

/* LUTUSE:0/1 — force-toggle whether lut_data[] is used for partial updates */
static void cmd_lutuse(char *args)
{
    if (!args || !*args) {
        ble_printf("LUTUSE:%s\r\n",
                   ssd1675a_get_use_custom_lut() ? "1 (custom)" : "0 (builtin)");
        return;
    }
    int en = atoi(args);
    ssd1675a_set_use_custom_lut(en != 0);
    ble_printf("LUTUSE:%s\r\n", en ? "1 (custom LUT active)" : "0 (builtin LUTs)");
}

/* LGET — dump current lut_data[] back to host as 7 lines of 10 bytes each.
 * Format: "LUT:N:XXXXXXXXXXXXXXXXXXXX\r\n"  (28 chars per line).
 * 28 chars fits within even the smallest BLE ATT MTU (23 bytes would fail,
 * but MTU is negotiated higher in practice; and with CONFIG_BT_L2CAP_TX_MTU=247
 * it is guaranteed). We bypass ble_printf() to avoid its 128-byte snprintf cap. */
static void cmd_lget(char *args)
{
    static const char hx[] = "0123456789ABCDEF";
    char ln[32];

    for (int chunk = 0; chunk < 7; chunk++) {
        ln[0] = 'L'; ln[1] = 'U'; ln[2] = 'T'; ln[3] = ':';
        ln[4] = '0' + chunk;
        ln[5] = ':';
        for (int j = 0; j < 10; j++) {
            uint8_t b = ssd1675a_get_lut_byte(chunk * 10 + j);
            ln[6 + j * 2]     = hx[b >> 4];
            ln[6 + j * 2 + 1] = hx[b & 0xF];
        }
        ln[26] = '\r'; ln[27] = '\n';
        ble_service_send(ln, 28);
    }
}

/* LTEST / LTEST 0 — start/stop LUT test animation mode */
static void cmd_ltest(char *args)
{
    if (args && *args == '0') {
        display_manager_set_screensaver_mode(SCREENSAVER_MODE_STATIC);
        display_manager_enable_screensaver(true);
        ble_printf("LUT test stopped\r\n");
    } else {
        display_manager_enable_screensaver(true);
        display_manager_set_screensaver_mode(SCREENSAVER_MODE_LUT_TEST);
        ble_printf("LUT test started (LTEST 0 to stop)\r\n");
    }
}

static int parse_partial_mode_name(const char *name)
{
    if (!name || !*name) return -1;

    if      (name[0] == '0' || strncasecmp(name, "TURBO",    5) == 0) return 0;
    else if (name[0] == '1' || strncasecmp(name, "BALANCED", 8) == 0) return 1;
    else if (name[0] == '2' || strncasecmp(name, "STABLE",   6) == 0) return 2;
    else if (name[0] == '3' || strncasecmp(name, "CLEAN",    5) == 0) return 3;
    else if (name[0] == '4' || strncasecmp(name, "TONE_DARK", 9) == 0 ||
             strncasecmp(name, "DARK", 4) == 0) return 4;
    else if (name[0] == '5' || strncasecmp(name, "TONE_LIGHT", 10) == 0 ||
             strncasecmp(name, "LIGHT", 5) == 0) return 5;
    else if (name[0] == '6' || strcasecmp(name, "TONE_BIDIR_FAST") == 0 ||
             strcasecmp(name, "BIDIR_FAST") == 0 ||
             strcasecmp(name, "BIDIR2") == 0) return 6;
    else if (name[0] == '7' || strcasecmp(name, "TONE_BIDIR") == 0 ||
             strcasecmp(name, "BIDIR") == 0 ||
             strcasecmp(name, "BIDIR4") == 0) return 7;
    else if (name[0] == '8' || strcasecmp(name, "TONE_SOFT_DARK") == 0 ||
             strcasecmp(name, "SOFT_DARK") == 0) return 8;
    else if (name[0] == '9' || strcasecmp(name, "TONE_SOFT_LIGHT") == 0 ||
             strcasecmp(name, "SOFT_LIGHT") == 0) return 9;

    return -1;
}

static const char *partial_mode_name(int mode)
{
    static const char *names[] = {
        "TURBO", "BALANCED", "STABLE", "CLEAN", "TONE_DARK", "TONE_LIGHT",
        "TONE_BIDIR_FAST", "TONE_BIDIR", "TONE_SOFT_DARK", "TONE_SOFT_LIGHT"
    };

    return (mode >= 0 && mode < (int)ARRAY_SIZE(names)) ? names[mode] : "?";
}

/* LUTSET:<name|n> — select built-in preset by name/index and disable custom LUT.
 * Accepted: TURBO/0, BALANCED/1, STABLE/2, CLEAN/3, TONE_DARK/4,
 * TONE_LIGHT/5, TONE_BIDIR_FAST/6, TONE_BIDIR/7 (case-insensitive). */
static void cmd_lutset(char *args)
{
    if (!args || !*args) {
        ble_printf("LUTSET: usage: TURBO|BALANCED|STABLE|CLEAN|TONE_DARK|TONE_LIGHT|TONE_BIDIR_FAST|TONE_BIDIR (0-7)\r\n");
        return;
    }
    int mode = parse_partial_mode_name(args);
    if (mode < 0) {
        ble_printf("LUTSET: unknown preset '%s'\r\n", args);
        return;
    }

    ssd1675a_set_use_custom_lut(false);
    display_manager_set_partial_mode(mode);
    ble_printf("LUTSET:%s (mode=%d, custom=off)\r\n", partial_mode_name(mode), mode);
}

/* VLUT:slot:base:off=val,off=val,... — define/activate/list/clear virtual LUT
 *   VLUT:0:4:35=01,36=01      — define slot 0 based on mode 4 (TONE_DARK), patch TA/TB to 1
 *   VLUT:0                     — activate slot 0
 *   VLUT:OFF                   — deactivate virtual LUT, revert to partial mode
 *   VLUT:LIST                  — show defined slots
 *   VLUT:CLEAR                 — clear all virtual slots
 */
static void cmd_vlut(char *args)
{
    if (!args || !*args) {
        ble_printf("VLUT: usage: slot:base:off=val,... | slot | OFF | LIST | CLEAR\r\n");
        return;
    }

    if (strcmp(args, "CLEAR") == 0 || strcmp(args, "clear") == 0) {
        ssd1675a_vlut_clear();
        ble_printf("VLUT:cleared\r\n");
        return;
    }

    if (strcmp(args, "OFF") == 0 || strcmp(args, "off") == 0) {
        ssd1675a_vlut_activate(-1);
        ble_printf("VLUT:off\r\n");
        return;
    }

    if (strcmp(args, "LIST") == 0 || strcmp(args, "list") == 0) {
        for (int i = 0; i < ssd1675a_vlut_get_count(); i++) {
            if (ssd1675a_vlut_slot_defined(i)) {
                ble_printf("VLUT[%d]: defined%s\r\n", i,
                           (ssd1675a_vlut_active() == i) ? " *active*" : "");
            }
        }
        if (ssd1675a_vlut_active() < 0) ble_printf("VLUT: none active\r\n");
        return;
    }

    /* Parse: could be just "slot" to activate, or "slot:base:patches" to define */
    char *p1 = strchr(args, ':');
    int slot = atoi(args);

    if (!p1) {
        /* Just a slot number — activate it */
        if (!ssd1675a_vlut_slot_defined(slot)) {
            ble_printf("VLUT:slot %d not defined\r\n", slot);
            return;
        }
        ssd1675a_vlut_activate(slot);
        ssd1675a_set_use_custom_lut(false);
        ble_printf("VLUT:%d active\r\n", slot);
        return;
    }

    /* Define: slot:base:off=val,off=val,... */
    char *p2 = strchr(p1 + 1, ':');
    if (!p2) {
        ble_printf("VLUT:err format slot:base:patches\r\n");
        return;
    }

    int base_mode = atoi(p1 + 1);
    char *patches_str = p2 + 1;

    uint8_t offsets[16], values[16];
    int count = 0;

    while (*patches_str && count < 16) {
        int off = (int)strtol(patches_str, &patches_str, 10);
        if (*patches_str != '=') break;
        patches_str++;
        int val = (int)strtol(patches_str, &patches_str, 16);
        if (off >= 0 && off < 70) {
            offsets[count] = (uint8_t)off;
            values[count]  = (uint8_t)val;
            count++;
        }
        if (*patches_str == ',') patches_str++;
    }

    int rc = ssd1675a_vlut_define(slot, (uint8_t)base_mode, offsets, values, count);
    if (rc < 0) {
        ble_printf("VLUT:err rc=%d\r\n", rc);
        return;
    }
    ble_printf("VLUT[%d]:defined base=%d patches=%d\r\n", slot, base_mode, count);
}

/* VSTREAM:start[:preset]|stop — enter/exit binary animation streaming mode */
static void cmd_vstream(char *args)
{
    if (!args || !*args) {
        ble_printf("VSTREAM:usage start[:TURBO|...|TONE_BIDIR_FAST|CUSTOM]|stop\r\n");
        return;
    }
    if (args[0] == '0' || strncmp(args, "stop", 4) == 0) {
        vs_exit_streaming(true);
        ble_printf("VSTREAM:stopped\r\n");
        return;
    }
    if (args[0] == '1' || strncmp(args, "start", 5) == 0) {
        const char *mode_arg = (args[0] == '1') ? args + 1 : args + 5;
        int mode = 0;  /* Backward-compatible default: TURBO. */

        while (*mode_arg == ':' || *mode_arg == '=' || *mode_arg == ' ') mode_arg++;
        bool use_custom = false;
        if (*mode_arg) {
            if (strncasecmp(mode_arg, "CUSTOM", 6) == 0) {
                /* Stream with the host-uploaded LUTW: table instead of a
                 * builtin preset — how a host A/Bs drive waveforms. */
                use_custom = true;
            } else {
                mode = parse_partial_mode_name(mode_arg);
                if (mode < 0) {
                    ble_printf("VSTREAM:bad lut '%s'\r\n", mode_arg);
                    return;
                }
            }
        }

        display_manager_enable_screensaver(false);
        k_msleep(50);  /* let screensaver thread finish any in-progress update */
        vs_fb = (uint16_t)plane_size();   /* frames are one plane of the detected panel */
        graphics_clear(GFX_WHITE);  /* ensure FB starts white before first RLE frame */
        display_manager_set_keep_on(true);
        display_manager_set_stream_write_red_plane(false);
        ssd1675a_set_use_custom_lut(use_custom);
        display_manager_set_partial_mode(mode);
        /* Prime the display before replying ready: wakes the controller from
         * deep sleep (where BUSY idles high and vs_flush_frame's wait_busy
         * would spin its full 8 s timeout on the first frame), charges the HV
         * rails and enters streaming mode. After this every frame only waits
         * for the previous LUT wave. */
        display_manager_update_partial();
        ble_service_set_streaming_mode(true);
        vs_state       = VS_IDLE;
        vs_frame_count = 0;
        vs_reset_frame();
        vs_has_crc     = false;
        vs_poisoned    = false;
        vstream_active = true;
        k_work_reschedule(&vs_watchdog_work, K_MSEC(VS_WATCHDOG_MS));
        ble_printf("VSTREAM:ready lut=%s type=RAW/RLE/DRLE/RAW2/RLE2/DRLE2 crc=opt(+0x40) half=opt(+0x20) fmt=AA55 tt LL LL [payload] [crcHi crcLo] BB stop=CCDD/CCDE\r\n",
                   partial_mode_name(mode));
        return;
    }
    ble_printf("VSTREAM:unknown\r\n");
}

static void cmd_reboot(char *args)
{
    (void)args;
    ble_printf("REBOOT\r\n");
    /* Save to flash before the (DFU) reboot: carries stats across even when
     * retained RAM does not survive (old MCUboot / power blip). The new
     * firmware consumes this snapshot and marks it spent. Flush the energy
     * estimator first so the final interval is captured in the snapshot. */
    display_manager_flush_energy();
    persist_save_to_flash();
    k_sleep(K_MSEC(100));   /* flush BLE TX + let flash write settle before reset */
    sys_reboot(SYS_REBOOT_COLD);
}

/* PROBE — identify the attached panel controller without knowing it up front.
 * Read-backs (status, OTP display option, user ID) plus a RAM-capacity probe:
 * 12000 B written through a 400-px-wide window. A 400x300-class controller
 * (SSD1619A, 15000 B/plane) returns every byte; a 160x296 one (SSD1675A/B,
 * 11840 B in both planes together) must lose some, whatever its address
 * wrapping does. Chip ID is 01 on both, hence the probe. */
static void probe_hex_line(const char *key, const uint8_t *buf, int n)
{
    static const char digits[] = "0123456789ABCDEF";
    char hex[2 * 16 + 1];
    int len = 0;
    for (int i = 0; i < n && i < 16; i++) {
        hex[len++] = digits[buf[i] >> 4];
        hex[len++] = digits[buf[i] & 0x0F];
    }
    hex[len] = '\0';
    ble_printf("PROBE:%s=%s\r\n", key, hex);
}

static void cmd_probe(char *args)
{
    (void)args;
    struct panel_probe_report r;
    display_manager_probe_panel(&r);

    const char *cls;
    if (r.ram.all_ff) {
        cls = "noread";                 /* data line never turned around */
    } else if (r.ram.match == r.ram.bytes) {
        cls = "400x300";                /* SSD1619A class */
    } else {
        cls = "160x296";                /* SSD1675 class */
    }
    ble_printf("PROBE:status=%02X chipid=%u busy=%u\r\n",
               r.status, r.status & 3u, (r.status >> 2) & 1u);
    probe_hex_line("otp", r.otp, sizeof(r.otp));
    probe_hex_line("uid", r.uid, sizeof(r.uid));
    ble_printf("PROBE:ram bytes=%d match=%d first_mismatch=%d\r\n",
               r.ram.bytes, r.ram.match, r.ram.first_mismatch);
    ble_printf("PROBE:class=%s panel=%s\r\n", cls, display_manager_panel_name());
}

/* RULER — geometry test screen for a freshly identified panel: border,
 * 10-px ticks, corner tags, diagonal, size in the middle. Full refresh. */
static void cmd_ruler(char *args)
{
    (void)args;
    display_manager_enable_screensaver(false);
    display_manager_show_ruler();
    ble_printf("RULER %dx%d panel=%s\r\n", graphics_get_width(), graphics_get_height(),
               display_manager_panel_name());
}

/* SCAN / SCAN:dummy,gate — panel scan timing (hex): 0x3A dummy line period
 * (00..7F) and 0x3B gate line width (0..F). Shorter = faster subframes, every
 * refresh and every vstream frame proportionally quicker, weaker drive.
 * Applied at the next init (every partial update re-inits). Not persisted. */
static void cmd_scan(char *args)
{
    if (args && *args) {
        char *comma = strchr(args, ',');
        if (!comma) { ble_printf("usage: SCAN:dummyHH,gateH\r\n"); return; }
        *comma = '\0';
        uint8_t dummy = (uint8_t)strtoul(args, NULL, 16);
        uint8_t gate = (uint8_t)strtoul(comma + 1, NULL, 16);
        ssd1675a_set_scan_timing(dummy, gate);
    }
    ble_printf("SCAN:dummy=%02X gate=%02X\r\n",
               ssd1675a_get_scan_dummy_line(), ssd1675a_get_scan_gate_width());
}

/* SPITEST — time the display bus: 15000 NOP command frames (pure bit-bang,
 * RAM untouched) and one real B/W plane load, in µs per byte. Diagnostic for
 * the port's write path; the plane load is what every vstream frame pays. */
static void cmd_spitest(char *args)
{
    (void)args;
    display_manager_enable_screensaver(false);
    k_msleep(100);
    ssd1675a_init_partial();
    uint32_t c0 = k_cycle_get_32();
    for (int i = 0; i < 15000; i++) {
        ssd1675a_port_write9(0x7F, false);   /* NOP */
    }
    uint32_t c1 = k_cycle_get_32();
    ssd1675a_display_buffer_fast(graphics_get_buffer());
    uint32_t c2 = k_cycle_get_32();
    uint32_t hz = sys_clock_hw_cycles_per_sec();
    uint32_t nop_us = (uint32_t)((uint64_t)(c1 - c0) * 1000000ULL / hz);
    uint32_t plane_us = (uint32_t)((uint64_t)(c2 - c1) * 1000000ULL / hz);
    ble_printf("SPITEST: nop15000=%uus (%u.%02uus/B) plane=%dB %uus (%u.%02uus/B) clk=%uHz\r\n",
               nop_us, nop_us / 15000, (nop_us % 15000) * 100 / 15000,
               plane_size(), plane_us, plane_us / plane_size(),
               (plane_us % plane_size()) * 100 / plane_size(), hz);
}

/* OTPLUT / OTPLUT:0|1 — full refreshes with the panel's factory OTP waveform
 * (1) or with the working LUT table (0). Takes effect at the next refresh. */
static void cmd_otplut(char *args)
{
    if (args && *args) {
        display_manager_set_full_refresh_otp(atoi(args) != 0);
    }
    ble_printf("OTPLUT=%d\r\n", display_manager_get_full_refresh_otp() ? 1 : 0);
}

/* SYSINFO — detailed system information for the host app (DFU page, etc.)
 * Reports: firmware version, build date, uptime, battery, energy consumed,
 * estimated current, MCUboot image version (from VERSION file). */
static void cmd_sysinfo(char *args)
{
    (void)args;
    /* 0 on a failed read: SYSINFO's bat= field is parsed as an unsigned
     * millivolt count by the host, so it must not go negative. */
    int mv = battery_read_mv();
    if (mv < 0) {
        mv = 0;
    }
    int64_t uptime_s = (int64_t)persist_uptime_sec();
    uint32_t mah_x1000 = display_manager_get_energy_mah_x1000();
    int cur_ua = display_manager_get_estimated_current_ua();

    ble_printf("SYSINFO:fw=%d.%d.%d",
               APP_VERSION_MAJOR, APP_VERSION_MINOR, APP_PATCHLEVEL);
#if defined(APP_BUILD_YEAR)
    ble_printf(" build=%d-%s%d-%s%d_%s%d:%s%d:%s%d",
               APP_BUILD_YEAR,
               APP_BUILD_MONTH < 10 ? "0" : "", APP_BUILD_MONTH,
               APP_BUILD_DAY   < 10 ? "0" : "", APP_BUILD_DAY,
               APP_BUILD_HOUR  < 10 ? "0" : "", APP_BUILD_HOUR,
               APP_BUILD_MIN   < 10 ? "0" : "", APP_BUILD_MIN,
               APP_BUILD_SEC   < 10 ? "0" : "", APP_BUILD_SEC);
#endif
    ble_printf(" uptime=%lld bat=%d mah=%u.%03u cur_ua=%d"
               " boots=%u fwupd=%u refr=%u refrfw=%u",
               (long long)uptime_s, mv,
               mah_x1000 / 1000, mah_x1000 % 1000, cur_ua,
               persist_boot_count(), persist_fw_update_count(),
               persist_refreshes_total(), persist_refreshes_since_fw());
    /* Identity + security on the same logical line (host buffers until '\n'). */
    ble_printf(" layout=%d serial=%s sec=%d authed=%d panel=%s phy=%d\r\n",
               APP_LAYOUT_ID, factory_serial(),
               secauth_enforced() ? 1 : 0, secauth_is_authed() ? 1 : 0,
               display_manager_panel_name(), ble_service_get_phy());
}

/* STATS — read persisted statistics (live RAM copy + flash record), for manual
 * inspection and the frontend. Line 1 = live values; line 2 = flash snapshot. */
static void cmd_stats(char *args)
{
    (void)args;
    struct persist_report r;
    persist_get_report(&r);

    uint32_t mah_x1000 = (uint32_t)(r.energy_uah_x1000 / 1000U);
    ble_printf("STATS:uptime=%lld wall=%lld boots=%u fwupd=%u refr=%u refrfw=%u mah=%u.%03u\r\n",
               (long long)r.uptime_total_sec, (long long)r.wall_unix,
               r.boot_count, r.fw_update_count,
               r.refreshes_total, r.refreshes_since_fw,
               mah_x1000 / 1000, mah_x1000 % 1000);
    ble_printf("STATS:flash=%s fl_uptime=%lld fl_wall=%lld\r\n",
               r.flash_present ? (r.flash_consumed ? "consumed" : "valid") : "none",
               (long long)r.flash_uptime_total_sec, (long long)r.flash_wall_unix);
}

/* DFU:START — host notifies that OTA upload is beginning.
 * DFU:DONE — host notifies that OTA upload completed.
 * Show a status screen so the user knows not to disconnect. */
/* The screens are rendered here, on the BLE RX thread, but the refresh itself
 * is handed to the display thread: a synchronous full refresh here used to
 * hold this thread for ~8 s right when the phone started streaming the image,
 * and the phone gave up on the stalled GATT exchange. */
static void cmd_dfu(char *args)
{
    int w = graphics_get_width();

    display_manager_enable_screensaver(false);
    graphics_clear(GFX_WHITE);

    if (strncmp(args, "START", 5) == 0) {
        graphics_fill_rect(0, 0, w, 18, GFX_BLACK);
        graphics_draw_string_color(w / 2 - 55, 5, "FIRMWARE UPDATE", GFX_WHITE);
        graphics_draw_string(w / 2 - 65, 35, "Receiving firmware...");
        graphics_draw_string(w / 2 - 70, 55, "Do NOT disconnect!");
        /* Progress bar outline */
        graphics_draw_rect(20, 80, w - 40, 16, GFX_BLACK);
        graphics_fill_rect(22, 82, 20, 12, GFX_BLACK);
        graphics_draw_string(w / 2 - 40, 105, "Please wait...");
        dfu_set_busy(true);
        display_manager_request_frame_update();
        ble_printf("DFU:ACK\r\n");
    } else if (strncmp(args, "DONE", 4) == 0) {
        graphics_fill_rect(0, 0, w, 18, GFX_BLACK);
        graphics_draw_string_color(w / 2 - 55, 5, "UPDATE COMPLETE", GFX_WHITE);
        graphics_draw_string(w / 2 - 50, 38, "Firmware loaded!");
        /* Full progress bar */
        graphics_draw_rect(20, 62, w - 40, 16, GFX_BLACK);
        graphics_fill_rect(22, 64, w - 44, 12, GFX_BLACK);
        graphics_draw_string_color(w / 2 - 75, 90, "Reboot to apply", GFX_RED);
        graphics_draw_string(w / 2 - 60, 110, "(or send REBOOT)");
        dfu_set_busy(false);
        display_manager_request_frame_update();
        ble_printf("DFU:DONE_ACK\r\n");
    } else {
        ble_printf("DFU:usage START|DONE\r\n");
    }
}

/* ── Security / identity commands ──────────────────────────────────────────
 * Deliberately basic: keeps random peers from pushing garbage. The strong
 * firmware-authenticity guarantee is the MCUboot signing key, not this gate. */
static void cmd_auth(char *args)
{
    if (!args || !*args) {
        char nonce_hex[33];
        if (secauth_make_challenge(nonce_hex, sizeof(nonce_hex)) == 0) {
            ble_printf("AUTH:CHAL %s\r\n", nonce_hex);
        } else {
            ble_printf("AUTH:ERR\r\n");
        }
        return;
    }
    ble_printf("AUTH:%s\r\n", secauth_verify(args) ? "OK" : "FAIL");
}

static void cmd_setkey(char *args)
{
    if (!args || !*args) { ble_printf("usage: SETKEY <32 hex>\r\n"); return; }
    int rc = secauth_set_key(args);
    if (rc == 0)       ble_printf("SETKEY:OK\r\n");
    else if (rc == -1) ble_printf("SETKEY:ERR auth required\r\n");
    else               ble_printf("SETKEY:ERR rc=%d\r\n", rc);
}

static void cmd_sec(char *args)
{
    if (!args || !*args) {
        ble_printf("SEC:%s authed=%d\r\n",
                   secauth_enforced() ? "ON" : "OFF", secauth_is_authed() ? 1 : 0);
        return;
    }
    if (strncasecmp(args, "ON", 2) == 0) {
        ble_printf("SEC:%s\r\n", secauth_set_enforced(true) == 0 ? "ON" : "ERR");
    } else if (strncasecmp(args, "OFF", 3) == 0) {
        ble_printf("SEC:%s\r\n", secauth_set_enforced(false) == 0 ? "OFF" : "ERR");
    } else {
        ble_printf("usage: SEC ON|OFF\r\n");
    }
}

static void cmd_name(char *args)
{
    if (!args || !*args) {
        ble_printf("NAME:%s\r\n", ble_service_get_device_name());
        return;
    }
    if (strcmp(args, "-") == 0) {   /* clear back to the default name */
        args = (char *)"";
    }
    (void)ble_service_set_custom_name(args);
    ble_printf("NAME:%s\r\n", ble_service_get_device_name());
}

/* Defined with the dispatch core below; BCAST re-uses it to turn the trailing
 * command line into an opcode + payload. */
static const struct shell_cmd *match_line(const char *line, const char **args_out);

static int mesh_hexnib(char c)
{
    if (c >= '0' && c <= '9') return c - '0';
    c |= 0x20;
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    return -1;
}

static void cmd_group(char *args)
{
    if (!args || !*args) {
        ble_printf("group=%u\r\n", mesh_get_group());
        return;
    }
    int g = atoi(args);
    if (g < 0 || g > 255) {
        ble_printf("group: 0..255\r\n");
        return;
    }
    mesh_set_group((uint8_t)g);
    ble_printf("group=%u\r\n", mesh_get_group());
}

static void cmd_meshrx(char *args)
{
    if (args && *args) {
        bool on;
        if (strcasecmp(args, "on") == 0 || strcmp(args, "1") == 0) {
            on = true;
        } else if (strcasecmp(args, "off") == 0 || strcmp(args, "0") == 0) {
            on = false;
        } else {
            ble_printf("usage: MESHRX / MESHRX ON|OFF\r\n");
            return;
        }
        mesh_set_rx(on);
    }
    /* An OFF node no longer hears the mesh, so a flooded MESHRX ON can never
     * reach it — say so up front instead of letting the fleet discover it. */
    ble_printf("meshrx=%s%s\r\n", mesh_get_rx() ? "on" : "off",
               mesh_get_rx() ? "" : " (re-enable over NUS only)");
}

/* PWR — the sleep profile and the pack behind it.
 *
 *   PWR                       report
 *   PWR:key=val[,key=val...]  change, persist, report
 *
 * Profile keys: day/night = redraw interval in minutes (0 = never by
 * schedule), from/to = night window in hours, advc/advp = idle advertising in
 * seconds for clock / picture mode.
 * Pack keys: chem = enum power_chem, ser/par = cells in series / strings in
 * parallel (1-4), cell = mAh of one cell (0 = unknown), newbat=1 = a fresh
 * pack went in (restarts the used-since counter). bat= is the older spelling
 * of cell= with par=1; btype= of chem=.
 * dry=1 computes the report for the given keys without saving or applying —
 * a host previews a choice with it before committing.
 *
 * Report, beyond the echo of the keys: night_now, next (seconds to the next
 * scheduled redraw, -1 = none), mv (pack voltage as the ADC sees it), vsoc
 * (charge from the chemistry curve, -1 = no curve), vsat (1 = the ADC is at
 * its 3600 mV ceiling and vsoc is a lower bound), used (mAh since the pack
 * epoch), est / base (average µA the model predicts for this profile and for
 * the everything-on baseline), days (left on the pack at est: -1 unknown
 * capacity, -2 mains — nothing depletes). */
static void cmd_pwr(char *args)
{
    struct power_profile p = *power_profile_get();
    struct power_battery b = *power_battery_get();
    bool newbat = false, dry = false, touched_bat = false;

    if (args && *args) {
        char *save = NULL;

        for (char *kv = strtok_r(args, ",", &save); kv; kv = strtok_r(NULL, ",", &save)) {
            char *eq = strchr(kv, '=');
            char *end = NULL;
            long val = eq ? strtol(eq + 1, &end, 10) : -1;

            if (!eq || !end || *end != '\0' || val < 0 || val > 65535) {
                ble_printf("usage: PWR / PWR:day=1,night=5,from=23,to=7,advc=2,advp=5,chem=1,ser=1,par=1,cell=370[,newbat=1][,dry=1]\r\n");
                return;
            }
            *eq = '\0';
            uint8_t v8 = (uint8_t)MIN(val, 255);
            if      (strcmp(kv, "day") == 0)    p.tick_day_min   = v8;
            else if (strcmp(kv, "night") == 0)  p.tick_night_min = v8;
            else if (strcmp(kv, "from") == 0)   p.night_from_h   = v8;
            else if (strcmp(kv, "to") == 0)     p.night_to_h     = v8;
            else if (strcmp(kv, "advc") == 0)   p.adv_clock_s    = v8;
            else if (strcmp(kv, "advp") == 0)   p.adv_picture_s  = v8;
            else if (strcmp(kv, "chem") == 0 || strcmp(kv, "btype") == 0) { b.chem = v8; touched_bat = true; }
            else if (strcmp(kv, "ser") == 0)    { b.series   = v8; touched_bat = true; }
            else if (strcmp(kv, "par") == 0)    { b.parallel = v8; touched_bat = true; }
            else if (strcmp(kv, "cell") == 0)   { b.cell_mah = (uint16_t)val; touched_bat = true; }
            else if (strcmp(kv, "bat") == 0)    { b.cell_mah = (uint16_t)val; b.parallel = 1; touched_bat = true; }
            else if (strcmp(kv, "newbat") == 0) { newbat = (val != 0); touched_bat = true; }
            else if (strcmp(kv, "dry") == 0)    dry = (val != 0);
            else {
                ble_printf("PWR: unknown key %s\r\n", kv);
                return;
            }
        }
        if (!dry) {
            if (power_profile_set(&p) != 0) {
                ble_printf("PWR: out of range (day/night 0-60, from/to 0-23, adv 1-10)\r\n");
                return;
            }
            if (touched_bat &&
                power_battery_set(b.chem, b.series, b.parallel, b.cell_mah, newbat) != 0) {
                ble_printf("PWR: bad pack (chem 0-7, ser/par 1-4)\r\n");
                return;
            }
        }
    }

    const struct power_profile *live = dry ? &p : power_profile_get();
    const struct power_battery *pack = dry ? &b : power_battery_get();
    bool picture = !display_manager_is_screensaver_active();
    int est  = display_manager_estimate_avg_ua(live, mesh_get_rx(), picture);
    int base = display_manager_estimate_avg_ua(power_profile_baseline(), true, picture);
    uint32_t used = power_battery_used_mah();
    uint32_t cap = power_battery_capacity_mah(pack);
    int mv = battery_read_mv();
    bool vsat = false;
    int vsoc = power_battery_soc_from_mv(pack, mv, &vsat);
    int days = -1;

    if (pack->chem == POWER_CHEM_MAINS) {
        days = -2;
    } else if (cap > 0 && est > 0) {
        uint32_t left = (cap > used) ? cap - used : 0;
        /* mAh / (µA * 24 h / 1000) = days */
        days = (int)((uint64_t)left * 1000U / ((uint32_t)est * 24U));
    }

    /* Two lines: ble_printf's buffer is 128 bytes and the whole report is
     * not. PWR: carries the profile and the estimates, PWRB: the pack. Both
     * repeat dry=1 so a host can tell a preview from the real thing. soc is
     * the combined figure the panel gauge shows (battery_percent), so the
     * page and the panel cannot disagree. */
    struct tm t;
    get_system_time(&t);
    ble_printf("PWR:day=%d night=%d from=%d to=%d advc=%d advp=%d night_now=%d next=%d est=%d base=%d days=%d%s\r\n",
               live->tick_day_min, live->tick_night_min, live->night_from_h, live->night_to_h,
               live->adv_clock_s, live->adv_picture_s,
               power_profile_is_night(t.tm_hour) ? 1 : 0,
               dry ? -1 : power_profile_seconds_to_tick(&t),
               est, base, days, dry ? " dry=1" : "");
    ble_printf("PWRB:chem=%u ser=%u par=%u cell=%u mv=%d vsoc=%d vsat=%d used=%u soc=%d%s\r\n",
               pack->chem, pack->series, pack->parallel, pack->cell_mah,
               mv, vsoc, vsat ? 1 : 0, (unsigned)used,
               dry ? -1 : battery_percent(mv), dry ? " dry=1" : "");
}

/* BCAST <all|g<N>|<6hex-id>> <CMD...> — flood a command to the fleet.
 * The trailing CMD is parsed exactly like a typed command, so the same opcode +
 * argument handling is reused (no duplicated command logic). */
static void cmd_bcast(char *args)
{
    if (!args || !*args) {
        ble_printf("usage: BCAST <all|g<N>|<6hex>> <CMD...>\r\n");
        return;
    }

    char *sp = strchr(args, ' ');
    if (!sp) {
        ble_printf("BCAST: need a command after target\r\n");
        return;
    }
    *sp = '\0';
    char *tok = args;
    char *cmdline = sp + 1;
    while (*cmdline == ' ') cmdline++;

    enum mesh_dst dst;
    uint8_t dstval[3] = {0};
    if (strcasecmp(tok, "all") == 0) {
        dst = MESH_DST_ALL;
    } else if ((tok[0] == 'g' || tok[0] == 'G') && tok[1]) {
        dst = MESH_DST_GROUP;
        dstval[0] = (uint8_t)atoi(tok + 1);
    } else if (strlen(tok) == 6) {
        for (int i = 0; i < 3; i++) {
            int hi = mesh_hexnib(tok[i * 2]);
            int lo = mesh_hexnib(tok[i * 2 + 1]);
            if (hi < 0 || lo < 0) {
                ble_printf("BCAST: bad id '%s'\r\n", tok);
                return;
            }
            dstval[i] = (uint8_t)((hi << 4) | lo);
        }
        dst = MESH_DST_ID;
    } else {
        ble_printf("BCAST: bad target '%s'\r\n", tok);
        return;
    }

    const char *payload = "";
    const struct shell_cmd *c = match_line(cmdline, &payload);
    if (!c) {
        ble_printf("BCAST: unknown cmd\r\n");
        return;
    }
    if (!(c->flags & CMD_MESH)) {
        ble_printf("BCAST: '%s' not broadcast-safe\r\n", c->name);
        return;
    }

    size_t plen = strlen(payload);
    int rc = plen > UINT8_MAX
             ? -EMSGSIZE
             : mesh_originate(dst, dstval, c->opcode,
                              (const uint8_t *)payload, (uint8_t)plen);
    const char *status = rc == 0 ? "queued"
                       : rc == -EMSGSIZE ? "args too long" : "full";
    ble_printf("BCAST op=%02X -> %s\r\n", c->opcode, status);
}

/* ── Command table ───────────────────────────────────────────────────────── */

const struct shell_cmd commands[] = {
    /* General */
    {OP_HELP,      "HELP",        cmd_help,       "List commands"},
    {OP_BATT,      "BATT",        cmd_batt,       "Read battery mV"},
    {OP_TIME,      "TIME",        cmd_time,       "Set time: HH:MM:SS DD.MM.YYYY", CMD_MESH},
    {OP_TIME,      "TIME=",       cmd_time_eq,    "Set time: TIME=HH:MM:SS (host compat)", CMD_MESH},
    /* Display */
    {OP_SAVER,     "SAVER",       cmd_saver,      "Enable screensaver", CMD_MESH},
    {OP_SS,        "SS:",         cmd_ss,         "Screensaver: SS:0/1", CMD_MESH},
    {OP_DSAVER,    "DSAVER",      cmd_dsaver,     "Dynamic saver: DSAVER 0/1", CMD_MESH},
    {OP_CLEAR,     "CLEAR",       cmd_cls,        "Clear display buffer", CMD_MESH},
    {OP_CLEAN,     "CLEAN",       cmd_clean,      "Run clean cycle (7×B/W/R)"},
    {OP_NUKE,      "NUKE:",       cmd_nuke,       "Deep ghost clear: NUKE:20 (default 20 cycles, ~15min)"},
    {OP_UPDATE,    "UPDATE",      cmd_update,     "Full display refresh", CMD_MESH},
    {OP_UPDATE,    "APPLY",       cmd_update,     "Full refresh (host compat alias for UPDATE)", CMD_MESH},
    {OP_FAST,      "FAST",        cmd_fast,       "Fast/partial update", CMD_MESH},
    {OP_FAPPLY,    "FAPPLY",      cmd_fapply,     "Push FW/RW frame buffers to display; FAPPLY RED stages RW: bytes as red on a single-plane panel", CMD_MESH},
    {OP_MODE,      "MODE:",       cmd_mode,       "Partial mode: 0=T 1=B 2=S 3=C 4=ToneDark 5=ToneLight 6=ToneBidirFast 7=ToneBidir 8=SoftDark 9=SoftLight", CMD_MESH},
    {OP_PALTEST,   "PALTEST",     cmd_paltest,    "Render B/W/R palette and spatial dither test"},
    {OP_TONETEST,  "TONETEST",    cmd_tonetest,   "Render physical gray accumulation test"},
    {OP_TEXT,      "TEXT:",       cmd_text,       "Draw text on display"},
    {OP_ROT,       "ROT:",        cmd_rot,        "Set rotation 0-3", CMD_MESH},
    {OP_ANIM,      "ANIM",        cmd_anim,       "Run bouncing-ball animation"},
    {OP_TEST,      "TEST",        cmd_test,       "Infinite partial stress test"},
    {OP_VSTREAM,   "VSTREAM:",    cmd_vstream,    "Binary stream: VSTREAM:start[:preset]|stop (then binary frames)"},
    /* LUT editor */
    {OP_LUTW,      "LUTW:",       cmd_lutw,       "Write full LUT: LUTW:HH..HH (140 hex)"},
    {OP_LW,        "LW:",         cmd_lw,         "Write N LUT bytes: LW:idx:HH.."},
    {OP_LBYTE,     "L:",          cmd_l_byte,     "LUT byte: L:n=HH / L:DUMP / L:RESET"},
    {OP_LUTUSE,    "LUTUSE:",     cmd_lutuse,     "Custom LUT toggle: LUTUSE:0/1", CMD_MESH},
    {OP_LUTSET,    "LUTSET:",     cmd_lutset,     "Select preset: TURBO|BALANCED|STABLE|CLEAN|TONE_DARK|TONE_LIGHT|TONE_BIDIR_FAST|TONE_BIDIR|TONE_SOFT_DARK|TONE_SOFT_LIGHT", CMD_MESH},
    {OP_VLUT,      "VLUT:",       cmd_vlut,       "Virtual LUT: VLUT:slot:base:off=val,... | VLUT:slot | VLUT:OFF | VLUT:LIST | VLUT:CLEAR"},
    {OP_LGET,      "LGET",        cmd_lget,       "Dump current LUT: replies LUT:0: + LUT:1: lines"},
    {OP_LTEST,     "LTEST",       cmd_ltest,      "LUT test animation: LTEST / LTEST 0"},
    {OP_HOST,      "HOST:",       cmd_host,       "Machine mode: HOST:1 (TELE: replies) HOST:0"},
    {OP_STAT,      "STAT",        cmd_stat,       "Telemetry snapshot: frame/last/min/max ms"},
    /* Frame buffers */
    {OP_FW,        "FW:",         cmd_fw,         "Write BW frame: FW:offset:HH.."},
    {OP_RW,        "RW:",         cmd_rw,         "Write Red frame: RW:offset:HH.. (single-plane panel: then FAPPLY RED, then FW:)"},
    /* System */
    {OP_REBOOT,    "REBOOT",      cmd_reboot,     "Cold reboot the device", CMD_MESH},
    {OP_SYSINFO,   "SYSINFO",     cmd_sysinfo,    "System info: version, uptime, battery, energy", CMD_NOAUTH},
    {OP_STATS,     "STATS",       cmd_stats,      "Persisted stats: live + flash record (present/valid/consumed)"},
    {OP_DFU,       "DFU:",        cmd_dfu,        "DFU display: DFU:START / DFU:DONE"},
    /* Mesh broadcast */
    {OP_BCAST,     "BCAST",       cmd_bcast,      "Flood a command: BCAST <all|g<N>|<6hex>> <CMD...>"},
    {OP_GROUP,     "GROUP",       cmd_group,      "Mesh group id: GROUP / GROUP <0-255>", CMD_MESH},
    {OP_MESHRX,    "MESHRX",      cmd_meshrx,     "Mesh receive: MESHRX / MESHRX ON|OFF (OFF saves ~0.2-0.3mA; node stops hearing floods)", CMD_MESH},
    {OP_PWR,       "PWR:",        cmd_pwr,        "Sleep profile + pack: PWR:day=1,night=5,from=23,to=7,advc=2,advp=5,chem=1,ser=1,par=1,cell=370[,newbat=1][,dry=1]", CMD_MESH},
    {OP_PWR,       "PWR",         cmd_pwr,        "Sleep profile: show (day/night redraw interval, night window, adv interval)", CMD_MESH},
    /* Security / identity */
    {OP_AUTH,      "AUTH",        cmd_auth,       "Auth: AUTH (get challenge) / AUTH <resp-hex>", CMD_NOAUTH},
    {OP_SETKEY,    "SETKEY",      cmd_setkey,     "Replace shared key: SETKEY <32 hex> (must be authed)"},
    {OP_SEC,       "SEC",         cmd_sec,        "Access gate: SEC / SEC ON / SEC OFF", CMD_MESH},
    {OP_NAME,      "NAME",        cmd_name,       "Device name: NAME / NAME <text> / NAME - (clear)", CMD_MESH},
    /* Debug */
    {OP_VCOM,      "VCOM=",       cmd_vcom,       "Set VCOM: VCOM=HH"},
    {OP_VCOM,      "DEBUG:VCOM=", cmd_debug_vcom, "Set VCOM (legacy)"},
    {OP_DEBUG_LUT, "DEBUG:LUT=",  cmd_debug_lut,  "Set LUT byte: DEBUG:LUT=idx:HH"},
    {OP_PROBE,     "PROBE",       cmd_probe,      "Identify panel controller: status/OTP/UID read-back + RAM capacity probe"},
    {OP_RULER,     "RULER",       cmd_ruler,      "Geometry test screen: border, 10px ticks, corner tags, diagonal"},
    {OP_OTPLUT,    "OTPLUT",      cmd_otplut,     "Full-refresh waveform: OTPLUT / OTPLUT:1 (factory OTP) / OTPLUT:0 (working LUT)"},
    {OP_SCAN,      "SCAN:",       cmd_scan,       "Scan timing (hex): SCAN:dummy,gate e.g. SCAN:35,4 (default) / SCAN:10,2 (faster)"},
    {OP_SCAN,      "SCAN",        cmd_scan,       "Show scan timing"},
    {OP_SPITEST,   "SPITEST",     cmd_spitest,    "Time the display bus: NOP burst + one plane load, us/byte"},
    {OP_INVALID, NULL, NULL, NULL}
};

/* ── Shared dispatch core ─────────────────────────────────────────────────
 * Both the text protocol and the binary opcode frame resolve to a registry
 * entry and then run it here, so the access gate and the handler call live in
 * exactly one place. */

static const struct shell_cmd *find_by_opcode(uint8_t opcode)
{
    if (opcode == OP_INVALID) {
        return NULL;
    }
    for (int i = 0; commands[i].name != NULL; i++) {
        if (commands[i].opcode == opcode) {
            return &commands[i];   /* first match wins (aliases share an opcode) */
        }
    }
    return NULL;
}

static void run_command(const struct shell_cmd *c, char *args)
{
    if (mesh_is_dispatch_thread()) {
        /* Over the air: the PDU's CMAC already proved fleet membership, so the
         * per-connection secauth gate does not apply. Only commands explicitly
         * marked broadcast-safe may run from a flood. */
        if (c->flags & CMD_MESH) {
            c->handler(args);
        }
        return;
    }

    /* Access gate: when enforcement is on, only NOAUTH commands (AUTH, SYSINFO)
     * run until the peer authenticates this connection. */
    if (secauth_enforced() && !secauth_is_authed() &&
        !(c->flags & CMD_NOAUTH)) {
        ble_printf("ERR:auth required (send AUTH)\r\n");
        return;
    }

    c->handler(args);
}

/* Prefix-match a text line to a registry entry, returning the entry and the
 * argument substring. Shared by the text dispatcher and BCAST (which re-uses it
 * to turn "BCAST all MODE:3" into the MODE opcode + "3" payload). */
static const struct shell_cmd *match_line(const char *line, const char **args_out)
{
    for (int i = 0; commands[i].name != NULL; i++) {
        const char *cmd = commands[i].name;

        /* One-byte reject before the calls. The registry is 54 entries and
         * "FW:" sits 32 of them in, so a frame upload — 62-313 lines, each
         * re-walking the table — was paying a strlen() plus a strncmp() call
         * per entry per line, thousands of them per frame. Comparing the first
         * character first drops all but the handful of entries that share it,
         * and cannot change the outcome: a differing first byte already
         * guarantees strncmp() is non-zero for any non-empty name. */
        if (cmd[0] != line[0]) continue;

        int cmd_len = (int)strlen(cmd);

        if (strncmp(line, cmd, cmd_len) != 0) continue;

        const char *args = line + cmd_len;
        char last = cmd[cmd_len - 1];

        /* Commands ending with ':' or '=' consume everything after the
         * separator; others require args to be absent or space-separated. */
        if (last != ':' && last != '=' && *args != '\0' && *args != ' ') continue;

        while (*args == ' ') args++;
        *args_out = args;
        return &commands[i];
    }
    return NULL;
}

/* Resolve a binary opcode frame to its handler. The single dispatch point that
 * the mesh layer (Phase 1) will also call for flooded commands. */
void cmd_dispatch_opcode(uint8_t opcode, char *args, enum cmd_origin origin)
{
    /* `origin` is not stored yet: Phase 1 will route replies by it, but a
     * single file-scope variable would be the wrong home — the mesh dispatch
     * thread and the BLE RX thread dispatch concurrently and would clobber
     * each other's value. It belongs in a per-dispatch context. */
    ARG_UNUSED(origin);

    const struct shell_cmd *c = find_by_opcode(opcode);
    if (c) {
        run_command(c, args ? args : "");
    } else {
        ble_printf("ERR:bad opcode %02X\r\n", opcode);
    }
}

/* ── Dispatch a single complete text line ────────────────────────────────── */

/* ── DFU busy gate ──────────────────────────────────────────────────────
 *
 * While an image is being transferred the BLE link is the transfer. Web
 * Bluetooth cannot run two GATT operations at once, and on our side every
 * text command runs on the BLE RX thread — a command that takes the display
 * lock, waits on a panel refresh or queues notifications behind a saturated
 * TX pool stalls the SMP exchange that is in flight, and the phone reports
 * "GATT operation failed for unknown reason" and aborts the update.
 *
 * So for the duration of a transfer the dispatcher accepts only what the
 * update itself needs — DFU:, REBOOT, SYSINFO, HOST: — and answers everything
 * else with one short BUSY:dfu line. The window opens on DFU:START or on the
 * first SMP upload chunk (mcumgr hook, so a host that never says DFU:START is
 * covered too) and closes on DFU:DONE, on the upload finishing or aborting,
 * on disconnect, or after ten idle minutes if the host simply vanished. */
static bool dfu_busy;
static struct k_work_delayable dfu_busy_timeout;
#define DFU_BUSY_TIMEOUT K_MINUTES(10)

static void dfu_busy_expire(struct k_work *work)
{
    ARG_UNUSED(work);
    dfu_busy = false;
}

static void dfu_set_busy(bool on)
{
    dfu_busy = on;
    if (on) {
        k_work_reschedule(&dfu_busy_timeout, DFU_BUSY_TIMEOUT);
    } else {
        k_work_cancel_delayable(&dfu_busy_timeout);
    }
}

static bool allowed_while_dfu(const char *line)
{
    return strncmp(line, "DFU:", 4) == 0 ||
           strcmp(line, "REBOOT") == 0 ||
           strncmp(line, "SYSINFO", 7) == 0 ||
           strncmp(line, "HOST:", 5) == 0;
}

#ifdef CONFIG_MCUMGR_MGMT_NOTIFICATION_HOOKS
static enum mgmt_cb_return dfu_mgmt_cb(uint32_t event, enum mgmt_cb_return prev_status,
                                       int32_t *rc, uint16_t *group, bool *abort_more,
                                       void *data, size_t data_size)
{
    ARG_UNUSED(prev_status); ARG_UNUSED(rc); ARG_UNUSED(group);
    ARG_UNUSED(abort_more); ARG_UNUSED(data); ARG_UNUSED(data_size);

    switch (event) {
    case MGMT_EVT_OP_IMG_MGMT_DFU_STARTED:
        dfu_set_busy(true);
        break;
    case MGMT_EVT_OP_IMG_MGMT_DFU_CHUNK:
        if (dfu_busy) {
            k_work_reschedule(&dfu_busy_timeout, DFU_BUSY_TIMEOUT);
        }
        break;
    case MGMT_EVT_OP_IMG_MGMT_DFU_STOPPED:
    case MGMT_EVT_OP_IMG_MGMT_DFU_PENDING:
        dfu_set_busy(false);
        break;
    default:
        break;
    }
    return MGMT_CB_OK;
}

static struct mgmt_callback dfu_mgmt_callback = {
    .callback = dfu_mgmt_cb,
    .event_id = MGMT_EVT_OP_IMG_MGMT_ALL,
};
#endif

static void dispatch_line(const char *line)
{
    const char *args = "";
    if (dfu_busy && !allowed_while_dfu(line)) {
        ble_printf("BUSY:dfu\r\n");
        return;
    }
    const struct shell_cmd *c = match_line(line, &args);
    if (c) {
        run_command(c, (char *)args);   /* text is an alias for the entry's opcode */
    } else {
        ble_printf("unknown cmd\r\n");
    }
}

/* ── Public API ──────────────────────────────────────────────────────────── */

void commands_init(void) {
    k_work_init_delayable(&vs_watchdog_work, vs_watchdog_handler);
    k_work_init_delayable(&dfu_busy_timeout, dfu_busy_expire);
#ifdef CONFIG_MCUMGR_MGMT_NOTIFICATION_HOOKS
    mgmt_callback_register(&dfu_mgmt_callback);
#endif
}

void commands_on_disconnect(void) {
    /* If a video/animation stream was active, tear it down and restore the
     * screensaver — the stream content is gone and the device should not sit
     * frozen on a half-rendered frame.
     *
     * If the device is in still-photo / image mode (screensaver already off,
     * no active vstream) the user intentionally left a tonal image on the
     * display.  A BLE disconnect must NOT wake the screensaver and overwrite
     * that image — the panel is bistable and the picture persists without
     * power.  We only clean up the binary-stream machine state. */
    if (vstream_active) {
        vs_exit_streaming(true);   /* stream was running → restore saver */
    } else {
        /* No stream active: just reset protocol state, leave saver as-is. */
        ble_service_set_streaming_mode(false);
        display_manager_set_stream_write_red_plane(false);
        k_work_cancel_delayable(&vs_watchdog_work);
        vs_state = VS_IDLE;
    }

    /* Clear session-scoped virtual LUT slots — they are temporary experiments
     * defined over BLE and should not persist across reconnections. */
    ssd1675a_vlut_clear();

    /* Drop the per-connection auth so the next peer must authenticate again. */
    secauth_session_reset();

    /* Discard any half-received text line or opcode frame from the old link. */
    rx_len = 0;
    rx_discard = false;
    if (rx_slot) {
        k_fifo_put(&cmd_free, rx_slot);
        rx_slot = NULL;
    }
    opc_state = OPC_NONE;
    if (opc_slot) {
        k_fifo_put(&cmd_free, opc_slot);
        opc_slot = NULL;
    }

    /* The transfer, if any, went with the link. */
    dfu_set_busy(false);

    /* Commands the old link queued must not run against the new one. */
    for (struct cmd_slot *slot; (slot = k_fifo_get(&cmd_ready, K_NO_WAIT)) != NULL;) {
        k_fifo_put(&cmd_free, slot);
    }
}

/* Feed one byte into the binary opcode-frame state machine. On the final byte
 * the frame is dispatched through the shared opcode path. */
static void opc_finish(void)
{
    opc_state = OPC_NONE;
    if (!opc_slot) {
        return;                     /* frame was being discarded */
    }
    opc_slot->is_opcode = true;
    opc_slot->opcode = opc_opcode;
    k_fifo_put(&cmd_ready, opc_slot);
    opc_slot = NULL;
}

static void opc_feed_byte(uint8_t b)
{
    switch (opc_state) {
    case OPC_WANT_OP:
        opc_opcode = b;
        opc_slot = k_fifo_get(&cmd_free, K_NO_WAIT);
        if (!opc_slot) {
            ble_printf("BUSY:cmd\r\n");
        }
        opc_state = OPC_WANT_LEN;
        break;
    case OPC_WANT_LEN:
        opc_len = b;
        opc_idx = 0;
        if (opc_len == 0) {
            if (opc_slot) {
                opc_slot->line[0] = '\0';
            }
            opc_finish();
        } else {
            opc_state = OPC_WANT_PAYLOAD;
        }
        break;
    case OPC_WANT_PAYLOAD:
        if (opc_slot && opc_idx < RX_BUF_SIZE - 1) {
            opc_slot->line[opc_idx] = (char)b;
        }
        opc_idx++;
        if (opc_idx >= opc_len) {
            if (opc_slot) {
                uint8_t n = MIN(opc_len, (uint8_t)(RX_BUF_SIZE - 1));
                opc_slot->line[n] = '\0';
            }
            opc_finish();
        }
        break;
    default:
        opc_state = OPC_NONE;
        break;
    }
}

/* ── Command execution thread ───────────────────────────────────────────
 *
 * Text commands used to run right where the bytes arrived: inside the BLE
 * host's RX thread (bt_receive_cb -> commands_process). Every second a
 * handler spent on the panel was a second the host could not service the
 * link — CLEAN (~60 s) and NUKE (minutes) outlasted the phone's 30 s ATT
 * timeout, the phone dropped the connection, and the tag stayed invisible
 * until the handler returned and the disconnect callback finally ran. An
 * infinite TEST took the radio down with it for good.
 *
 * So the RX thread now only assembles lines and hands them over; this thread
 * runs them. A slow handler stalls the queue, not the radio: the link stays
 * up, SMP keeps flowing, and the next command is either queued (two deep) or
 * answered BUSY:cmd at once. REBOOT and SYSINFO are executed inline on the RX
 * thread so they work even while this thread is stuck in a dev loop — the
 * escape hatch that used to require pulling the battery. Binary paths
 * (vstream bytes, opcode frames) still run on the RX thread: they are fast by
 * construction. The mesh dispatch thread keeps its own path. */
static void cmd_thread(void *p1, void *p2, void *p3)
{
    ARG_UNUSED(p1); ARG_UNUSED(p2); ARG_UNUSED(p3);

    for (int i = 0; i < CMD_QUEUE_DEPTH; i++) {
        k_fifo_put(&cmd_free, &cmd_slots[i]);
    }
    while (1) {
        struct cmd_slot *slot = k_fifo_get(&cmd_ready, K_FOREVER);

        if (slot->is_opcode) {
            cmd_dispatch_opcode(slot->opcode, slot->line, CMD_ORIGIN_NUS);
        } else {
            dispatch_line(slot->line);
        }
        slot->is_opcode = false;
        k_fifo_put(&cmd_free, slot);
    }
}
K_THREAD_DEFINE(cmd_tid, 1280, cmd_thread, NULL, NULL, NULL, 7, 0, 0);

/* Whatever must keep working while the command thread is busy for minutes. */
static bool inline_on_rx_thread(const char *line)
{
    return strcmp(line, "REBOOT") == 0 || strncmp(line, "SYSINFO", 7) == 0;
}

static void enqueue_line(struct cmd_slot *slot)
{
    slot->is_opcode = false;
    if (inline_on_rx_thread(slot->line)) {
        dispatch_line(slot->line);
        k_fifo_put(&cmd_free, slot);
        return;
    }
    k_fifo_put(&cmd_ready, slot);
}

void commands_process(const void *data, uint16_t len)
{
    const uint8_t *p = (const uint8_t *)data;
    for (uint16_t i = 0; i < len; i++) {
        if (vstream_active) {
            vs_process_byte(p[i]);
            continue;
        }
        if (opc_state != OPC_NONE) {
            opc_feed_byte(p[i]);
            continue;
        }
        /* A frame sentinel is only valid at a line boundary, so it can never be
         * mistaken for a byte inside a half-typed text command. */
        if (rx_len == 0 && p[i] == OPC_MAGIC) {
            opc_state = OPC_WANT_OP;
            continue;
        }
        char c = (char)p[i];
        if (c == '\r') continue;
        if (rx_discard) {
            /* Both slots are busy behind a slow command: this line is lost;
             * the BUSY:cmd already went out when it started. */
            if (c == '\n') rx_discard = false;
            continue;
        }
        if (!rx_slot) {
            if (c == '\n') continue;          /* empty line, nothing to queue */
            rx_slot = k_fifo_get(&cmd_free, K_NO_WAIT);
            if (!rx_slot) {
                rx_discard = true;
                ble_printf("BUSY:cmd\r\n");
                continue;
            }
            rx_len = 0;
        }
        if (c == '\n') {
            rx_slot->line[rx_len] = '\0';
            rx_len = 0;
            if (rx_slot->line[0] != '\0') {
                enqueue_line(rx_slot);
            } else {
                k_fifo_put(&cmd_free, rx_slot);
            }
            rx_slot = NULL;
        } else if (rx_len < RX_BUF_SIZE - 1) {
            rx_slot->line[rx_len++] = c;
        }
    }
}
